<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: iap/iap.proto

namespace Iap;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>iap.BasketPosition</code>
 */
class BasketPosition extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string extension_name = 1 [json_name = "extensionName"];</code>
     */
    protected $extension_name = '';
    /**
     * Generated from protobuf field <code>string in_app_feature_identifier = 2 [json_name = "inAppFeatureIdentifier"];</code>
     */
    protected $in_app_feature_identifier = '';
    /**
     * Generated from protobuf field <code>string variant = 3 [json_name = "variant"];</code>
     */
    protected $variant = '';
    /**
     * Generated from protobuf field <code>double net_price = 4 [json_name = "netPrice"];</code>
     */
    protected $net_price = 0.0;
    /**
     * Generated from protobuf field <code>double prorated_net_price = 5 [json_name = "proratedNetPrice"];</code>
     */
    protected $prorated_net_price = 0.0;
    /**
     * Generated from protobuf field <code>double tax_value = 6 [json_name = "taxValue"];</code>
     */
    protected $tax_value = 0.0;
    /**
     * Generated from protobuf field <code>double gross_price = 7 [json_name = "grossPrice"];</code>
     */
    protected $gross_price = 0.0;
    /**
     * Generated from protobuf field <code>double tax_rate = 8 [json_name = "taxRate"];</code>
     */
    protected $tax_rate = 0.0;
    /**
     * Generated from protobuf field <code>optional .iap.SubscriptionChange subscription_change = 9 [json_name = "subscriptionChange"];</code>
     */
    protected $subscription_change = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $extension_name
     *     @type string $in_app_feature_identifier
     *     @type string $variant
     *     @type float $net_price
     *     @type float $prorated_net_price
     *     @type float $tax_value
     *     @type float $gross_price
     *     @type float $tax_rate
     *     @type \Iap\SubscriptionChange $subscription_change
     * }
     */
    public function __construct($data = NULL) {
        \Iap\GPBMetadata\Iap::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string extension_name = 1 [json_name = "extensionName"];</code>
     * @return string
     */
    public function getExtensionName()
    {
        return $this->extension_name;
    }

    /**
     * Generated from protobuf field <code>string extension_name = 1 [json_name = "extensionName"];</code>
     * @param string $var
     * @return $this
     */
    public function setExtensionName($var)
    {
        GPBUtil::checkString($var, True);
        $this->extension_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string in_app_feature_identifier = 2 [json_name = "inAppFeatureIdentifier"];</code>
     * @return string
     */
    public function getInAppFeatureIdentifier()
    {
        return $this->in_app_feature_identifier;
    }

    /**
     * Generated from protobuf field <code>string in_app_feature_identifier = 2 [json_name = "inAppFeatureIdentifier"];</code>
     * @param string $var
     * @return $this
     */
    public function setInAppFeatureIdentifier($var)
    {
        GPBUtil::checkString($var, True);
        $this->in_app_feature_identifier = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string variant = 3 [json_name = "variant"];</code>
     * @return string
     */
    public function getVariant()
    {
        return $this->variant;
    }

    /**
     * Generated from protobuf field <code>string variant = 3 [json_name = "variant"];</code>
     * @param string $var
     * @return $this
     */
    public function setVariant($var)
    {
        GPBUtil::checkString($var, True);
        $this->variant = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double net_price = 4 [json_name = "netPrice"];</code>
     * @return float
     */
    public function getNetPrice()
    {
        return $this->net_price;
    }

    /**
     * Generated from protobuf field <code>double net_price = 4 [json_name = "netPrice"];</code>
     * @param float $var
     * @return $this
     */
    public function setNetPrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->net_price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double prorated_net_price = 5 [json_name = "proratedNetPrice"];</code>
     * @return float
     */
    public function getProratedNetPrice()
    {
        return $this->prorated_net_price;
    }

    /**
     * Generated from protobuf field <code>double prorated_net_price = 5 [json_name = "proratedNetPrice"];</code>
     * @param float $var
     * @return $this
     */
    public function setProratedNetPrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->prorated_net_price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double tax_value = 6 [json_name = "taxValue"];</code>
     * @return float
     */
    public function getTaxValue()
    {
        return $this->tax_value;
    }

    /**
     * Generated from protobuf field <code>double tax_value = 6 [json_name = "taxValue"];</code>
     * @param float $var
     * @return $this
     */
    public function setTaxValue($var)
    {
        GPBUtil::checkDouble($var);
        $this->tax_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double gross_price = 7 [json_name = "grossPrice"];</code>
     * @return float
     */
    public function getGrossPrice()
    {
        return $this->gross_price;
    }

    /**
     * Generated from protobuf field <code>double gross_price = 7 [json_name = "grossPrice"];</code>
     * @param float $var
     * @return $this
     */
    public function setGrossPrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->gross_price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double tax_rate = 8 [json_name = "taxRate"];</code>
     * @return float
     */
    public function getTaxRate()
    {
        return $this->tax_rate;
    }

    /**
     * Generated from protobuf field <code>double tax_rate = 8 [json_name = "taxRate"];</code>
     * @param float $var
     * @return $this
     */
    public function setTaxRate($var)
    {
        GPBUtil::checkDouble($var);
        $this->tax_rate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .iap.SubscriptionChange subscription_change = 9 [json_name = "subscriptionChange"];</code>
     * @return \Iap\SubscriptionChange|null
     */
    public function getSubscriptionChange()
    {
        return $this->subscription_change;
    }

    public function hasSubscriptionChange()
    {
        return isset($this->subscription_change);
    }

    public function clearSubscriptionChange()
    {
        unset($this->subscription_change);
    }

    /**
     * Generated from protobuf field <code>optional .iap.SubscriptionChange subscription_change = 9 [json_name = "subscriptionChange"];</code>
     * @param \Iap\SubscriptionChange $var
     * @return $this
     */
    public function setSubscriptionChange($var)
    {
        GPBUtil::checkMessage($var, \Iap\SubscriptionChange::class);
        $this->subscription_change = $var;

        return $this;
    }

}

