<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: iap/iap.proto

namespace Iap;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>iap.CalculateBasketRequest</code>
 */
class CalculateBasketRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string extension_name = 1 [json_name = "extensionName"];</code>
     */
    protected $extension_name = '';
    /**
     * Generated from protobuf field <code>string in_app_feature_identifier = 2 [json_name = "inAppFeatureIdentifier"];</code>
     */
    protected $in_app_feature_identifier = '';
    /**
     * Generated from protobuf field <code>string variant = 3 [json_name = "variant"];</code>
     */
    protected $variant = '';
    /**
     * Generated from protobuf field <code>string language = 4 [json_name = "language"];</code>
     */
    protected $language = '';
    /**
     * Generated from protobuf field <code>string domain = 5 [json_name = "domain"];</code>
     */
    protected $domain = '';
    /**
     * Generated from protobuf field <code>string shopware_version = 6 [json_name = "shopwareVersion"];</code>
     */
    protected $shopware_version = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $extension_name
     *     @type string $in_app_feature_identifier
     *     @type string $variant
     *     @type string $language
     *     @type string $domain
     *     @type string $shopware_version
     * }
     */
    public function __construct($data = NULL) {
        \Iap\GPBMetadata\Iap::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string extension_name = 1 [json_name = "extensionName"];</code>
     * @return string
     */
    public function getExtensionName()
    {
        return $this->extension_name;
    }

    /**
     * Generated from protobuf field <code>string extension_name = 1 [json_name = "extensionName"];</code>
     * @param string $var
     * @return $this
     */
    public function setExtensionName($var)
    {
        GPBUtil::checkString($var, True);
        $this->extension_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string in_app_feature_identifier = 2 [json_name = "inAppFeatureIdentifier"];</code>
     * @return string
     */
    public function getInAppFeatureIdentifier()
    {
        return $this->in_app_feature_identifier;
    }

    /**
     * Generated from protobuf field <code>string in_app_feature_identifier = 2 [json_name = "inAppFeatureIdentifier"];</code>
     * @param string $var
     * @return $this
     */
    public function setInAppFeatureIdentifier($var)
    {
        GPBUtil::checkString($var, True);
        $this->in_app_feature_identifier = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string variant = 3 [json_name = "variant"];</code>
     * @return string
     */
    public function getVariant()
    {
        return $this->variant;
    }

    /**
     * Generated from protobuf field <code>string variant = 3 [json_name = "variant"];</code>
     * @param string $var
     * @return $this
     */
    public function setVariant($var)
    {
        GPBUtil::checkString($var, True);
        $this->variant = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string language = 4 [json_name = "language"];</code>
     * @return string
     */
    public function getLanguage()
    {
        return $this->language;
    }

    /**
     * Generated from protobuf field <code>string language = 4 [json_name = "language"];</code>
     * @param string $var
     * @return $this
     */
    public function setLanguage($var)
    {
        GPBUtil::checkString($var, True);
        $this->language = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string domain = 5 [json_name = "domain"];</code>
     * @return string
     */
    public function getDomain()
    {
        return $this->domain;
    }

    /**
     * Generated from protobuf field <code>string domain = 5 [json_name = "domain"];</code>
     * @param string $var
     * @return $this
     */
    public function setDomain($var)
    {
        GPBUtil::checkString($var, True);
        $this->domain = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string shopware_version = 6 [json_name = "shopwareVersion"];</code>
     * @return string
     */
    public function getShopwareVersion()
    {
        return $this->shopware_version;
    }

    /**
     * Generated from protobuf field <code>string shopware_version = 6 [json_name = "shopwareVersion"];</code>
     * @param string $var
     * @return $this
     */
    public function setShopwareVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->shopware_version = $var;

        return $this;
    }

}

