<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: iap/iap.proto

namespace Iap;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>iap.GetInAppPlansRequest</code>
 */
class GetInAppPlansRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string extension_name = 1 [json_name = "extensionName"];</code>
     */
    protected $extension_name = '';
    /**
     * Generated from protobuf field <code>string language = 2 [json_name = "language"];</code>
     */
    protected $language = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $extension_name
     *     @type string $language
     * }
     */
    public function __construct($data = NULL) {
        \Iap\GPBMetadata\Iap::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string extension_name = 1 [json_name = "extensionName"];</code>
     * @return string
     */
    public function getExtensionName()
    {
        return $this->extension_name;
    }

    /**
     * Generated from protobuf field <code>string extension_name = 1 [json_name = "extensionName"];</code>
     * @param string $var
     * @return $this
     */
    public function setExtensionName($var)
    {
        GPBUtil::checkString($var, True);
        $this->extension_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string language = 2 [json_name = "language"];</code>
     * @return string
     */
    public function getLanguage()
    {
        return $this->language;
    }

    /**
     * Generated from protobuf field <code>string language = 2 [json_name = "language"];</code>
     * @param string $var
     * @return $this
     */
    public function setLanguage($var)
    {
        GPBUtil::checkString($var, True);
        $this->language = $var;

        return $this;
    }

}

