// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: iap/iap.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Struct } from "../google/protobuf/struct";

export const protobufPackage = "iap";

export interface CalculateBasketRequest {
  extensionName: string;
  inAppFeatureIdentifier: string;
  variant: string;
  language: string;
  domain: string;
  shopwareVersion: string;
}

export interface CalculateBasketResponse {
  taxRate: number;
  positions: BasketPosition[];
}

export interface BasketPosition {
  extensionName: string;
  inAppFeatureIdentifier: string;
  variant: string;
  netPrice: number;
  proratedNetPrice: number;
  taxValue: number;
  grossPrice: number;
  taxRate: number;
  subscriptionChange?: SubscriptionChange | undefined;
}

export interface SubscriptionChange {
  type: string;
  currentInAppFeatureIdentifier: string;
}

export interface PlaceOrderRequest {
  taxRate: number;
  positions: BasketPosition[];
  language: string;
  domain: string;
  shopwareVersion: string;
}

export interface PlaceOrderResponse {
  /** Define fields based on successful order response, usually empty or confirmation */
  success: boolean;
}

export interface GetInAppFeatureRequest {
  extensionName: string;
  inAppFeatureIdentifier: string;
  language: string;
  domain: string;
  shopwareVersion: string;
}

export interface GetInAppFeatureResponse {
  payload: { [key: string]: any } | undefined;
}

export interface GetInAppPlansRequest {
  extensionName: string;
  language: string;
}

export interface GetInAppPlansResponse {
  plans: InAppPlan[];
}

export interface InAppPlan {
  id: number;
  identifier: string;
  name: string;
  description: string;
  serviceConditions?: string | undefined;
  websiteGtc?: string | undefined;
  priceModels: PriceModel[];
  priceModel: PriceModel | undefined;
  group: PlanGroup | undefined;
  status: string;
}

export interface PriceModel {
  variant: string;
  type: string;
  price: number;
  conditionsType?: string | undefined;
  duration: number;
  oneTimeOnly?: boolean | undefined;
}

export interface PlanGroup {
  identifier: string;
  name: string;
}

function createBaseCalculateBasketRequest(): CalculateBasketRequest {
  return { extensionName: "", inAppFeatureIdentifier: "", variant: "", language: "", domain: "", shopwareVersion: "" };
}

export const CalculateBasketRequest: MessageFns<CalculateBasketRequest> = {
  encode(message: CalculateBasketRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.extensionName !== "") {
      writer.uint32(10).string(message.extensionName);
    }
    if (message.inAppFeatureIdentifier !== "") {
      writer.uint32(18).string(message.inAppFeatureIdentifier);
    }
    if (message.variant !== "") {
      writer.uint32(26).string(message.variant);
    }
    if (message.language !== "") {
      writer.uint32(34).string(message.language);
    }
    if (message.domain !== "") {
      writer.uint32(42).string(message.domain);
    }
    if (message.shopwareVersion !== "") {
      writer.uint32(50).string(message.shopwareVersion);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CalculateBasketRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCalculateBasketRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.extensionName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.inAppFeatureIdentifier = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.variant = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.language = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.domain = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.shopwareVersion = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CalculateBasketRequest {
    return {
      extensionName: isSet(object.extensionName) ? globalThis.String(object.extensionName) : "",
      inAppFeatureIdentifier: isSet(object.inAppFeatureIdentifier)
        ? globalThis.String(object.inAppFeatureIdentifier)
        : "",
      variant: isSet(object.variant) ? globalThis.String(object.variant) : "",
      language: isSet(object.language) ? globalThis.String(object.language) : "",
      domain: isSet(object.domain) ? globalThis.String(object.domain) : "",
      shopwareVersion: isSet(object.shopwareVersion) ? globalThis.String(object.shopwareVersion) : "",
    };
  },

  toJSON(message: CalculateBasketRequest): unknown {
    const obj: any = {};
    if (message.extensionName !== "") {
      obj.extensionName = message.extensionName;
    }
    if (message.inAppFeatureIdentifier !== "") {
      obj.inAppFeatureIdentifier = message.inAppFeatureIdentifier;
    }
    if (message.variant !== "") {
      obj.variant = message.variant;
    }
    if (message.language !== "") {
      obj.language = message.language;
    }
    if (message.domain !== "") {
      obj.domain = message.domain;
    }
    if (message.shopwareVersion !== "") {
      obj.shopwareVersion = message.shopwareVersion;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CalculateBasketRequest>, I>>(base?: I): CalculateBasketRequest {
    return CalculateBasketRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CalculateBasketRequest>, I>>(object: I): CalculateBasketRequest {
    const message = createBaseCalculateBasketRequest();
    message.extensionName = object.extensionName ?? "";
    message.inAppFeatureIdentifier = object.inAppFeatureIdentifier ?? "";
    message.variant = object.variant ?? "";
    message.language = object.language ?? "";
    message.domain = object.domain ?? "";
    message.shopwareVersion = object.shopwareVersion ?? "";
    return message;
  },
};

function createBaseCalculateBasketResponse(): CalculateBasketResponse {
  return { taxRate: 0, positions: [] };
}

export const CalculateBasketResponse: MessageFns<CalculateBasketResponse> = {
  encode(message: CalculateBasketResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.taxRate !== 0) {
      writer.uint32(9).double(message.taxRate);
    }
    for (const v of message.positions) {
      BasketPosition.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CalculateBasketResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCalculateBasketResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.taxRate = reader.double();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.positions.push(BasketPosition.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CalculateBasketResponse {
    return {
      taxRate: isSet(object.taxRate) ? globalThis.Number(object.taxRate) : 0,
      positions: globalThis.Array.isArray(object?.positions)
        ? object.positions.map((e: any) => BasketPosition.fromJSON(e))
        : [],
    };
  },

  toJSON(message: CalculateBasketResponse): unknown {
    const obj: any = {};
    if (message.taxRate !== 0) {
      obj.taxRate = message.taxRate;
    }
    if (message.positions?.length) {
      obj.positions = message.positions.map((e) => BasketPosition.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CalculateBasketResponse>, I>>(base?: I): CalculateBasketResponse {
    return CalculateBasketResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CalculateBasketResponse>, I>>(object: I): CalculateBasketResponse {
    const message = createBaseCalculateBasketResponse();
    message.taxRate = object.taxRate ?? 0;
    message.positions = object.positions?.map((e) => BasketPosition.fromPartial(e)) || [];
    return message;
  },
};

function createBaseBasketPosition(): BasketPosition {
  return {
    extensionName: "",
    inAppFeatureIdentifier: "",
    variant: "",
    netPrice: 0,
    proratedNetPrice: 0,
    taxValue: 0,
    grossPrice: 0,
    taxRate: 0,
    subscriptionChange: undefined,
  };
}

export const BasketPosition: MessageFns<BasketPosition> = {
  encode(message: BasketPosition, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.extensionName !== "") {
      writer.uint32(10).string(message.extensionName);
    }
    if (message.inAppFeatureIdentifier !== "") {
      writer.uint32(18).string(message.inAppFeatureIdentifier);
    }
    if (message.variant !== "") {
      writer.uint32(26).string(message.variant);
    }
    if (message.netPrice !== 0) {
      writer.uint32(33).double(message.netPrice);
    }
    if (message.proratedNetPrice !== 0) {
      writer.uint32(41).double(message.proratedNetPrice);
    }
    if (message.taxValue !== 0) {
      writer.uint32(49).double(message.taxValue);
    }
    if (message.grossPrice !== 0) {
      writer.uint32(57).double(message.grossPrice);
    }
    if (message.taxRate !== 0) {
      writer.uint32(65).double(message.taxRate);
    }
    if (message.subscriptionChange !== undefined) {
      SubscriptionChange.encode(message.subscriptionChange, writer.uint32(74).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BasketPosition {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBasketPosition();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.extensionName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.inAppFeatureIdentifier = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.variant = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.netPrice = reader.double();
          continue;
        }
        case 5: {
          if (tag !== 41) {
            break;
          }

          message.proratedNetPrice = reader.double();
          continue;
        }
        case 6: {
          if (tag !== 49) {
            break;
          }

          message.taxValue = reader.double();
          continue;
        }
        case 7: {
          if (tag !== 57) {
            break;
          }

          message.grossPrice = reader.double();
          continue;
        }
        case 8: {
          if (tag !== 65) {
            break;
          }

          message.taxRate = reader.double();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.subscriptionChange = SubscriptionChange.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BasketPosition {
    return {
      extensionName: isSet(object.extensionName) ? globalThis.String(object.extensionName) : "",
      inAppFeatureIdentifier: isSet(object.inAppFeatureIdentifier)
        ? globalThis.String(object.inAppFeatureIdentifier)
        : "",
      variant: isSet(object.variant) ? globalThis.String(object.variant) : "",
      netPrice: isSet(object.netPrice) ? globalThis.Number(object.netPrice) : 0,
      proratedNetPrice: isSet(object.proratedNetPrice) ? globalThis.Number(object.proratedNetPrice) : 0,
      taxValue: isSet(object.taxValue) ? globalThis.Number(object.taxValue) : 0,
      grossPrice: isSet(object.grossPrice) ? globalThis.Number(object.grossPrice) : 0,
      taxRate: isSet(object.taxRate) ? globalThis.Number(object.taxRate) : 0,
      subscriptionChange: isSet(object.subscriptionChange)
        ? SubscriptionChange.fromJSON(object.subscriptionChange)
        : undefined,
    };
  },

  toJSON(message: BasketPosition): unknown {
    const obj: any = {};
    if (message.extensionName !== "") {
      obj.extensionName = message.extensionName;
    }
    if (message.inAppFeatureIdentifier !== "") {
      obj.inAppFeatureIdentifier = message.inAppFeatureIdentifier;
    }
    if (message.variant !== "") {
      obj.variant = message.variant;
    }
    if (message.netPrice !== 0) {
      obj.netPrice = message.netPrice;
    }
    if (message.proratedNetPrice !== 0) {
      obj.proratedNetPrice = message.proratedNetPrice;
    }
    if (message.taxValue !== 0) {
      obj.taxValue = message.taxValue;
    }
    if (message.grossPrice !== 0) {
      obj.grossPrice = message.grossPrice;
    }
    if (message.taxRate !== 0) {
      obj.taxRate = message.taxRate;
    }
    if (message.subscriptionChange !== undefined) {
      obj.subscriptionChange = SubscriptionChange.toJSON(message.subscriptionChange);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BasketPosition>, I>>(base?: I): BasketPosition {
    return BasketPosition.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BasketPosition>, I>>(object: I): BasketPosition {
    const message = createBaseBasketPosition();
    message.extensionName = object.extensionName ?? "";
    message.inAppFeatureIdentifier = object.inAppFeatureIdentifier ?? "";
    message.variant = object.variant ?? "";
    message.netPrice = object.netPrice ?? 0;
    message.proratedNetPrice = object.proratedNetPrice ?? 0;
    message.taxValue = object.taxValue ?? 0;
    message.grossPrice = object.grossPrice ?? 0;
    message.taxRate = object.taxRate ?? 0;
    message.subscriptionChange = (object.subscriptionChange !== undefined && object.subscriptionChange !== null)
      ? SubscriptionChange.fromPartial(object.subscriptionChange)
      : undefined;
    return message;
  },
};

function createBaseSubscriptionChange(): SubscriptionChange {
  return { type: "", currentInAppFeatureIdentifier: "" };
}

export const SubscriptionChange: MessageFns<SubscriptionChange> = {
  encode(message: SubscriptionChange, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== "") {
      writer.uint32(10).string(message.type);
    }
    if (message.currentInAppFeatureIdentifier !== "") {
      writer.uint32(18).string(message.currentInAppFeatureIdentifier);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubscriptionChange {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubscriptionChange();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.currentInAppFeatureIdentifier = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SubscriptionChange {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      currentInAppFeatureIdentifier: isSet(object.currentInAppFeatureIdentifier)
        ? globalThis.String(object.currentInAppFeatureIdentifier)
        : "",
    };
  },

  toJSON(message: SubscriptionChange): unknown {
    const obj: any = {};
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.currentInAppFeatureIdentifier !== "") {
      obj.currentInAppFeatureIdentifier = message.currentInAppFeatureIdentifier;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SubscriptionChange>, I>>(base?: I): SubscriptionChange {
    return SubscriptionChange.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SubscriptionChange>, I>>(object: I): SubscriptionChange {
    const message = createBaseSubscriptionChange();
    message.type = object.type ?? "";
    message.currentInAppFeatureIdentifier = object.currentInAppFeatureIdentifier ?? "";
    return message;
  },
};

function createBasePlaceOrderRequest(): PlaceOrderRequest {
  return { taxRate: 0, positions: [], language: "", domain: "", shopwareVersion: "" };
}

export const PlaceOrderRequest: MessageFns<PlaceOrderRequest> = {
  encode(message: PlaceOrderRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.taxRate !== 0) {
      writer.uint32(9).double(message.taxRate);
    }
    for (const v of message.positions) {
      BasketPosition.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.language !== "") {
      writer.uint32(26).string(message.language);
    }
    if (message.domain !== "") {
      writer.uint32(34).string(message.domain);
    }
    if (message.shopwareVersion !== "") {
      writer.uint32(42).string(message.shopwareVersion);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PlaceOrderRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePlaceOrderRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.taxRate = reader.double();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.positions.push(BasketPosition.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.language = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.domain = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.shopwareVersion = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PlaceOrderRequest {
    return {
      taxRate: isSet(object.taxRate) ? globalThis.Number(object.taxRate) : 0,
      positions: globalThis.Array.isArray(object?.positions)
        ? object.positions.map((e: any) => BasketPosition.fromJSON(e))
        : [],
      language: isSet(object.language) ? globalThis.String(object.language) : "",
      domain: isSet(object.domain) ? globalThis.String(object.domain) : "",
      shopwareVersion: isSet(object.shopwareVersion) ? globalThis.String(object.shopwareVersion) : "",
    };
  },

  toJSON(message: PlaceOrderRequest): unknown {
    const obj: any = {};
    if (message.taxRate !== 0) {
      obj.taxRate = message.taxRate;
    }
    if (message.positions?.length) {
      obj.positions = message.positions.map((e) => BasketPosition.toJSON(e));
    }
    if (message.language !== "") {
      obj.language = message.language;
    }
    if (message.domain !== "") {
      obj.domain = message.domain;
    }
    if (message.shopwareVersion !== "") {
      obj.shopwareVersion = message.shopwareVersion;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PlaceOrderRequest>, I>>(base?: I): PlaceOrderRequest {
    return PlaceOrderRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PlaceOrderRequest>, I>>(object: I): PlaceOrderRequest {
    const message = createBasePlaceOrderRequest();
    message.taxRate = object.taxRate ?? 0;
    message.positions = object.positions?.map((e) => BasketPosition.fromPartial(e)) || [];
    message.language = object.language ?? "";
    message.domain = object.domain ?? "";
    message.shopwareVersion = object.shopwareVersion ?? "";
    return message;
  },
};

function createBasePlaceOrderResponse(): PlaceOrderResponse {
  return { success: false };
}

export const PlaceOrderResponse: MessageFns<PlaceOrderResponse> = {
  encode(message: PlaceOrderResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PlaceOrderResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePlaceOrderResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PlaceOrderResponse {
    return { success: isSet(object.success) ? globalThis.Boolean(object.success) : false };
  },

  toJSON(message: PlaceOrderResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PlaceOrderResponse>, I>>(base?: I): PlaceOrderResponse {
    return PlaceOrderResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PlaceOrderResponse>, I>>(object: I): PlaceOrderResponse {
    const message = createBasePlaceOrderResponse();
    message.success = object.success ?? false;
    return message;
  },
};

function createBaseGetInAppFeatureRequest(): GetInAppFeatureRequest {
  return { extensionName: "", inAppFeatureIdentifier: "", language: "", domain: "", shopwareVersion: "" };
}

export const GetInAppFeatureRequest: MessageFns<GetInAppFeatureRequest> = {
  encode(message: GetInAppFeatureRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.extensionName !== "") {
      writer.uint32(10).string(message.extensionName);
    }
    if (message.inAppFeatureIdentifier !== "") {
      writer.uint32(18).string(message.inAppFeatureIdentifier);
    }
    if (message.language !== "") {
      writer.uint32(26).string(message.language);
    }
    if (message.domain !== "") {
      writer.uint32(34).string(message.domain);
    }
    if (message.shopwareVersion !== "") {
      writer.uint32(42).string(message.shopwareVersion);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetInAppFeatureRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetInAppFeatureRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.extensionName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.inAppFeatureIdentifier = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.language = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.domain = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.shopwareVersion = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetInAppFeatureRequest {
    return {
      extensionName: isSet(object.extensionName) ? globalThis.String(object.extensionName) : "",
      inAppFeatureIdentifier: isSet(object.inAppFeatureIdentifier)
        ? globalThis.String(object.inAppFeatureIdentifier)
        : "",
      language: isSet(object.language) ? globalThis.String(object.language) : "",
      domain: isSet(object.domain) ? globalThis.String(object.domain) : "",
      shopwareVersion: isSet(object.shopwareVersion) ? globalThis.String(object.shopwareVersion) : "",
    };
  },

  toJSON(message: GetInAppFeatureRequest): unknown {
    const obj: any = {};
    if (message.extensionName !== "") {
      obj.extensionName = message.extensionName;
    }
    if (message.inAppFeatureIdentifier !== "") {
      obj.inAppFeatureIdentifier = message.inAppFeatureIdentifier;
    }
    if (message.language !== "") {
      obj.language = message.language;
    }
    if (message.domain !== "") {
      obj.domain = message.domain;
    }
    if (message.shopwareVersion !== "") {
      obj.shopwareVersion = message.shopwareVersion;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetInAppFeatureRequest>, I>>(base?: I): GetInAppFeatureRequest {
    return GetInAppFeatureRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetInAppFeatureRequest>, I>>(object: I): GetInAppFeatureRequest {
    const message = createBaseGetInAppFeatureRequest();
    message.extensionName = object.extensionName ?? "";
    message.inAppFeatureIdentifier = object.inAppFeatureIdentifier ?? "";
    message.language = object.language ?? "";
    message.domain = object.domain ?? "";
    message.shopwareVersion = object.shopwareVersion ?? "";
    return message;
  },
};

function createBaseGetInAppFeatureResponse(): GetInAppFeatureResponse {
  return { payload: undefined };
}

export const GetInAppFeatureResponse: MessageFns<GetInAppFeatureResponse> = {
  encode(message: GetInAppFeatureResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.payload !== undefined) {
      Struct.encode(Struct.wrap(message.payload), writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetInAppFeatureResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetInAppFeatureResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.payload = Struct.unwrap(Struct.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetInAppFeatureResponse {
    return { payload: isObject(object.payload) ? object.payload : undefined };
  },

  toJSON(message: GetInAppFeatureResponse): unknown {
    const obj: any = {};
    if (message.payload !== undefined) {
      obj.payload = message.payload;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetInAppFeatureResponse>, I>>(base?: I): GetInAppFeatureResponse {
    return GetInAppFeatureResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetInAppFeatureResponse>, I>>(object: I): GetInAppFeatureResponse {
    const message = createBaseGetInAppFeatureResponse();
    message.payload = object.payload ?? undefined;
    return message;
  },
};

function createBaseGetInAppPlansRequest(): GetInAppPlansRequest {
  return { extensionName: "", language: "" };
}

export const GetInAppPlansRequest: MessageFns<GetInAppPlansRequest> = {
  encode(message: GetInAppPlansRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.extensionName !== "") {
      writer.uint32(10).string(message.extensionName);
    }
    if (message.language !== "") {
      writer.uint32(18).string(message.language);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetInAppPlansRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetInAppPlansRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.extensionName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.language = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetInAppPlansRequest {
    return {
      extensionName: isSet(object.extensionName) ? globalThis.String(object.extensionName) : "",
      language: isSet(object.language) ? globalThis.String(object.language) : "",
    };
  },

  toJSON(message: GetInAppPlansRequest): unknown {
    const obj: any = {};
    if (message.extensionName !== "") {
      obj.extensionName = message.extensionName;
    }
    if (message.language !== "") {
      obj.language = message.language;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetInAppPlansRequest>, I>>(base?: I): GetInAppPlansRequest {
    return GetInAppPlansRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetInAppPlansRequest>, I>>(object: I): GetInAppPlansRequest {
    const message = createBaseGetInAppPlansRequest();
    message.extensionName = object.extensionName ?? "";
    message.language = object.language ?? "";
    return message;
  },
};

function createBaseGetInAppPlansResponse(): GetInAppPlansResponse {
  return { plans: [] };
}

export const GetInAppPlansResponse: MessageFns<GetInAppPlansResponse> = {
  encode(message: GetInAppPlansResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.plans) {
      InAppPlan.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetInAppPlansResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetInAppPlansResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.plans.push(InAppPlan.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetInAppPlansResponse {
    return {
      plans: globalThis.Array.isArray(object?.plans) ? object.plans.map((e: any) => InAppPlan.fromJSON(e)) : [],
    };
  },

  toJSON(message: GetInAppPlansResponse): unknown {
    const obj: any = {};
    if (message.plans?.length) {
      obj.plans = message.plans.map((e) => InAppPlan.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetInAppPlansResponse>, I>>(base?: I): GetInAppPlansResponse {
    return GetInAppPlansResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetInAppPlansResponse>, I>>(object: I): GetInAppPlansResponse {
    const message = createBaseGetInAppPlansResponse();
    message.plans = object.plans?.map((e) => InAppPlan.fromPartial(e)) || [];
    return message;
  },
};

function createBaseInAppPlan(): InAppPlan {
  return {
    id: 0,
    identifier: "",
    name: "",
    description: "",
    serviceConditions: undefined,
    websiteGtc: undefined,
    priceModels: [],
    priceModel: undefined,
    group: undefined,
    status: "",
  };
}

export const InAppPlan: MessageFns<InAppPlan> = {
  encode(message: InAppPlan, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.identifier !== "") {
      writer.uint32(18).string(message.identifier);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(34).string(message.description);
    }
    if (message.serviceConditions !== undefined) {
      writer.uint32(42).string(message.serviceConditions);
    }
    if (message.websiteGtc !== undefined) {
      writer.uint32(50).string(message.websiteGtc);
    }
    for (const v of message.priceModels) {
      PriceModel.encode(v!, writer.uint32(58).fork()).join();
    }
    if (message.priceModel !== undefined) {
      PriceModel.encode(message.priceModel, writer.uint32(66).fork()).join();
    }
    if (message.group !== undefined) {
      PlanGroup.encode(message.group, writer.uint32(74).fork()).join();
    }
    if (message.status !== "") {
      writer.uint32(82).string(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InAppPlan {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInAppPlan();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.identifier = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.serviceConditions = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.websiteGtc = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.priceModels.push(PriceModel.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.priceModel = PriceModel.decode(reader, reader.uint32());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.group = PlanGroup.decode(reader, reader.uint32());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.status = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InAppPlan {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      identifier: isSet(object.identifier) ? globalThis.String(object.identifier) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      serviceConditions: isSet(object.serviceConditions) ? globalThis.String(object.serviceConditions) : undefined,
      websiteGtc: isSet(object.websiteGtc) ? globalThis.String(object.websiteGtc) : undefined,
      priceModels: globalThis.Array.isArray(object?.priceModels)
        ? object.priceModels.map((e: any) => PriceModel.fromJSON(e))
        : [],
      priceModel: isSet(object.priceModel) ? PriceModel.fromJSON(object.priceModel) : undefined,
      group: isSet(object.group) ? PlanGroup.fromJSON(object.group) : undefined,
      status: isSet(object.status) ? globalThis.String(object.status) : "",
    };
  },

  toJSON(message: InAppPlan): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.identifier !== "") {
      obj.identifier = message.identifier;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.serviceConditions !== undefined) {
      obj.serviceConditions = message.serviceConditions;
    }
    if (message.websiteGtc !== undefined) {
      obj.websiteGtc = message.websiteGtc;
    }
    if (message.priceModels?.length) {
      obj.priceModels = message.priceModels.map((e) => PriceModel.toJSON(e));
    }
    if (message.priceModel !== undefined) {
      obj.priceModel = PriceModel.toJSON(message.priceModel);
    }
    if (message.group !== undefined) {
      obj.group = PlanGroup.toJSON(message.group);
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InAppPlan>, I>>(base?: I): InAppPlan {
    return InAppPlan.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InAppPlan>, I>>(object: I): InAppPlan {
    const message = createBaseInAppPlan();
    message.id = object.id ?? 0;
    message.identifier = object.identifier ?? "";
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    message.serviceConditions = object.serviceConditions ?? undefined;
    message.websiteGtc = object.websiteGtc ?? undefined;
    message.priceModels = object.priceModels?.map((e) => PriceModel.fromPartial(e)) || [];
    message.priceModel = (object.priceModel !== undefined && object.priceModel !== null)
      ? PriceModel.fromPartial(object.priceModel)
      : undefined;
    message.group = (object.group !== undefined && object.group !== null)
      ? PlanGroup.fromPartial(object.group)
      : undefined;
    message.status = object.status ?? "";
    return message;
  },
};

function createBasePriceModel(): PriceModel {
  return { variant: "", type: "", price: 0, conditionsType: undefined, duration: 0, oneTimeOnly: undefined };
}

export const PriceModel: MessageFns<PriceModel> = {
  encode(message: PriceModel, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.variant !== "") {
      writer.uint32(10).string(message.variant);
    }
    if (message.type !== "") {
      writer.uint32(18).string(message.type);
    }
    if (message.price !== 0) {
      writer.uint32(25).double(message.price);
    }
    if (message.conditionsType !== undefined) {
      writer.uint32(34).string(message.conditionsType);
    }
    if (message.duration !== 0) {
      writer.uint32(40).int32(message.duration);
    }
    if (message.oneTimeOnly !== undefined) {
      writer.uint32(48).bool(message.oneTimeOnly);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PriceModel {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePriceModel();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.variant = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.price = reader.double();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.conditionsType = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.duration = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.oneTimeOnly = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PriceModel {
    return {
      variant: isSet(object.variant) ? globalThis.String(object.variant) : "",
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      price: isSet(object.price) ? globalThis.Number(object.price) : 0,
      conditionsType: isSet(object.conditionsType) ? globalThis.String(object.conditionsType) : undefined,
      duration: isSet(object.duration) ? globalThis.Number(object.duration) : 0,
      oneTimeOnly: isSet(object.oneTimeOnly) ? globalThis.Boolean(object.oneTimeOnly) : undefined,
    };
  },

  toJSON(message: PriceModel): unknown {
    const obj: any = {};
    if (message.variant !== "") {
      obj.variant = message.variant;
    }
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.price !== 0) {
      obj.price = message.price;
    }
    if (message.conditionsType !== undefined) {
      obj.conditionsType = message.conditionsType;
    }
    if (message.duration !== 0) {
      obj.duration = Math.round(message.duration);
    }
    if (message.oneTimeOnly !== undefined) {
      obj.oneTimeOnly = message.oneTimeOnly;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PriceModel>, I>>(base?: I): PriceModel {
    return PriceModel.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PriceModel>, I>>(object: I): PriceModel {
    const message = createBasePriceModel();
    message.variant = object.variant ?? "";
    message.type = object.type ?? "";
    message.price = object.price ?? 0;
    message.conditionsType = object.conditionsType ?? undefined;
    message.duration = object.duration ?? 0;
    message.oneTimeOnly = object.oneTimeOnly ?? undefined;
    return message;
  },
};

function createBasePlanGroup(): PlanGroup {
  return { identifier: "", name: "" };
}

export const PlanGroup: MessageFns<PlanGroup> = {
  encode(message: PlanGroup, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.identifier !== "") {
      writer.uint32(10).string(message.identifier);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PlanGroup {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePlanGroup();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.identifier = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PlanGroup {
    return {
      identifier: isSet(object.identifier) ? globalThis.String(object.identifier) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
    };
  },

  toJSON(message: PlanGroup): unknown {
    const obj: any = {};
    if (message.identifier !== "") {
      obj.identifier = message.identifier;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PlanGroup>, I>>(base?: I): PlanGroup {
    return PlanGroup.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PlanGroup>, I>>(object: I): PlanGroup {
    const message = createBasePlanGroup();
    message.identifier = object.identifier ?? "";
    message.name = object.name ?? "";
    return message;
  },
};

/**
 * IAPService provides in-app purchase operations for Shopware extensions.
 * All methods require OAuth authentication via metadata headers unless overridden at method level.
 */
export type IAPServiceService = typeof IAPServiceService;
export const IAPServiceService = {
  /**
   * CalculateBasket calculates pricing for a basket of in-app purchases.
   * Returns tax rates and itemized positions with pricing details.
   */
  calculateBasket: {
    path: "/iap.IAPService/CalculateBasket",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CalculateBasketRequest) => Buffer.from(CalculateBasketRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => CalculateBasketRequest.decode(value),
    responseSerialize: (value: CalculateBasketResponse) => Buffer.from(CalculateBasketResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => CalculateBasketResponse.decode(value),
  },
  /**
   * PlaceOrder finalizes an in-app purchase order.
   * Requires a previously calculated basket with valid positions.
   */
  placeOrder: {
    path: "/iap.IAPService/PlaceOrder",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: PlaceOrderRequest) => Buffer.from(PlaceOrderRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => PlaceOrderRequest.decode(value),
    responseSerialize: (value: PlaceOrderResponse) => Buffer.from(PlaceOrderResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => PlaceOrderResponse.decode(value),
  },
  /**
   * GetInAppFeature retrieves details about a specific in-app feature.
   * Returns feature configuration and pricing variants.
   */
  getInAppFeature: {
    path: "/iap.IAPService/GetInAppFeature",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetInAppFeatureRequest) => Buffer.from(GetInAppFeatureRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => GetInAppFeatureRequest.decode(value),
    responseSerialize: (value: GetInAppFeatureResponse) => Buffer.from(GetInAppFeatureResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => GetInAppFeatureResponse.decode(value),
  },
  /**
   * GetInAppPlans retrieves all in-app plans for a specific extension.
   * This is a public API that uses M2M authentication (no user OAuth token required).
   */
  getInAppPlans: {
    path: "/iap.IAPService/GetInAppPlans",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetInAppPlansRequest) => Buffer.from(GetInAppPlansRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => GetInAppPlansRequest.decode(value),
    responseSerialize: (value: GetInAppPlansResponse) => Buffer.from(GetInAppPlansResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => GetInAppPlansResponse.decode(value),
  },
} as const;

export interface IAPServiceServer extends UntypedServiceImplementation {
  /**
   * CalculateBasket calculates pricing for a basket of in-app purchases.
   * Returns tax rates and itemized positions with pricing details.
   */
  calculateBasket: handleUnaryCall<CalculateBasketRequest, CalculateBasketResponse>;
  /**
   * PlaceOrder finalizes an in-app purchase order.
   * Requires a previously calculated basket with valid positions.
   */
  placeOrder: handleUnaryCall<PlaceOrderRequest, PlaceOrderResponse>;
  /**
   * GetInAppFeature retrieves details about a specific in-app feature.
   * Returns feature configuration and pricing variants.
   */
  getInAppFeature: handleUnaryCall<GetInAppFeatureRequest, GetInAppFeatureResponse>;
  /**
   * GetInAppPlans retrieves all in-app plans for a specific extension.
   * This is a public API that uses M2M authentication (no user OAuth token required).
   */
  getInAppPlans: handleUnaryCall<GetInAppPlansRequest, GetInAppPlansResponse>;
}

export interface IAPServiceClient extends Client {
  /**
   * CalculateBasket calculates pricing for a basket of in-app purchases.
   * Returns tax rates and itemized positions with pricing details.
   */
  calculateBasket(
    request: CalculateBasketRequest,
    callback: (error: ServiceError | null, response: CalculateBasketResponse) => void,
  ): ClientUnaryCall;
  calculateBasket(
    request: CalculateBasketRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CalculateBasketResponse) => void,
  ): ClientUnaryCall;
  calculateBasket(
    request: CalculateBasketRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CalculateBasketResponse) => void,
  ): ClientUnaryCall;
  /**
   * PlaceOrder finalizes an in-app purchase order.
   * Requires a previously calculated basket with valid positions.
   */
  placeOrder(
    request: PlaceOrderRequest,
    callback: (error: ServiceError | null, response: PlaceOrderResponse) => void,
  ): ClientUnaryCall;
  placeOrder(
    request: PlaceOrderRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: PlaceOrderResponse) => void,
  ): ClientUnaryCall;
  placeOrder(
    request: PlaceOrderRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: PlaceOrderResponse) => void,
  ): ClientUnaryCall;
  /**
   * GetInAppFeature retrieves details about a specific in-app feature.
   * Returns feature configuration and pricing variants.
   */
  getInAppFeature(
    request: GetInAppFeatureRequest,
    callback: (error: ServiceError | null, response: GetInAppFeatureResponse) => void,
  ): ClientUnaryCall;
  getInAppFeature(
    request: GetInAppFeatureRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetInAppFeatureResponse) => void,
  ): ClientUnaryCall;
  getInAppFeature(
    request: GetInAppFeatureRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetInAppFeatureResponse) => void,
  ): ClientUnaryCall;
  /**
   * GetInAppPlans retrieves all in-app plans for a specific extension.
   * This is a public API that uses M2M authentication (no user OAuth token required).
   */
  getInAppPlans(
    request: GetInAppPlansRequest,
    callback: (error: ServiceError | null, response: GetInAppPlansResponse) => void,
  ): ClientUnaryCall;
  getInAppPlans(
    request: GetInAppPlansRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetInAppPlansResponse) => void,
  ): ClientUnaryCall;
  getInAppPlans(
    request: GetInAppPlansRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetInAppPlansResponse) => void,
  ): ClientUnaryCall;
}

export const IAPServiceClient = makeGenericClientConstructor(IAPServiceService, "iap.IAPService") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): IAPServiceClient;
  service: typeof IAPServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
