// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: iap/iap.proto

package iap

import (
	_ "github.com/shopware/transaction-gateway-protos/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculateBasketRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ExtensionName          string                 `protobuf:"bytes,1,opt,name=extension_name,json=extensionName,proto3" json:"extension_name,omitempty"`
	InAppFeatureIdentifier string                 `protobuf:"bytes,2,opt,name=in_app_feature_identifier,json=inAppFeatureIdentifier,proto3" json:"in_app_feature_identifier,omitempty"`
	Variant                string                 `protobuf:"bytes,3,opt,name=variant,proto3" json:"variant,omitempty"`
	Language               string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Domain                 string                 `protobuf:"bytes,5,opt,name=domain,proto3" json:"domain,omitempty"`
	ShopwareVersion        string                 `protobuf:"bytes,6,opt,name=shopware_version,json=shopwareVersion,proto3" json:"shopware_version,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CalculateBasketRequest) Reset() {
	*x = CalculateBasketRequest{}
	mi := &file_iap_iap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateBasketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateBasketRequest) ProtoMessage() {}

func (x *CalculateBasketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iap_iap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateBasketRequest.ProtoReflect.Descriptor instead.
func (*CalculateBasketRequest) Descriptor() ([]byte, []int) {
	return file_iap_iap_proto_rawDescGZIP(), []int{0}
}

func (x *CalculateBasketRequest) GetExtensionName() string {
	if x != nil {
		return x.ExtensionName
	}
	return ""
}

func (x *CalculateBasketRequest) GetInAppFeatureIdentifier() string {
	if x != nil {
		return x.InAppFeatureIdentifier
	}
	return ""
}

func (x *CalculateBasketRequest) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

func (x *CalculateBasketRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CalculateBasketRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CalculateBasketRequest) GetShopwareVersion() string {
	if x != nil {
		return x.ShopwareVersion
	}
	return ""
}

type CalculateBasketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaxRate       float64                `protobuf:"fixed64,1,opt,name=tax_rate,json=taxRate,proto3" json:"tax_rate,omitempty"`
	Positions     []*BasketPosition      `protobuf:"bytes,2,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateBasketResponse) Reset() {
	*x = CalculateBasketResponse{}
	mi := &file_iap_iap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateBasketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateBasketResponse) ProtoMessage() {}

func (x *CalculateBasketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iap_iap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateBasketResponse.ProtoReflect.Descriptor instead.
func (*CalculateBasketResponse) Descriptor() ([]byte, []int) {
	return file_iap_iap_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateBasketResponse) GetTaxRate() float64 {
	if x != nil {
		return x.TaxRate
	}
	return 0
}

func (x *CalculateBasketResponse) GetPositions() []*BasketPosition {
	if x != nil {
		return x.Positions
	}
	return nil
}

type BasketPosition struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ExtensionName          string                 `protobuf:"bytes,1,opt,name=extension_name,json=extensionName,proto3" json:"extension_name,omitempty"`
	InAppFeatureIdentifier string                 `protobuf:"bytes,2,opt,name=in_app_feature_identifier,json=inAppFeatureIdentifier,proto3" json:"in_app_feature_identifier,omitempty"`
	Variant                string                 `protobuf:"bytes,3,opt,name=variant,proto3" json:"variant,omitempty"`
	NetPrice               float64                `protobuf:"fixed64,4,opt,name=net_price,json=netPrice,proto3" json:"net_price,omitempty"`
	ProratedNetPrice       float64                `protobuf:"fixed64,5,opt,name=prorated_net_price,json=proratedNetPrice,proto3" json:"prorated_net_price,omitempty"`
	TaxValue               float64                `protobuf:"fixed64,6,opt,name=tax_value,json=taxValue,proto3" json:"tax_value,omitempty"`
	GrossPrice             float64                `protobuf:"fixed64,7,opt,name=gross_price,json=grossPrice,proto3" json:"gross_price,omitempty"`
	TaxRate                float64                `protobuf:"fixed64,8,opt,name=tax_rate,json=taxRate,proto3" json:"tax_rate,omitempty"`
	SubscriptionChange     *SubscriptionChange    `protobuf:"bytes,9,opt,name=subscription_change,json=subscriptionChange,proto3,oneof" json:"subscription_change,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BasketPosition) Reset() {
	*x = BasketPosition{}
	mi := &file_iap_iap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasketPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasketPosition) ProtoMessage() {}

func (x *BasketPosition) ProtoReflect() protoreflect.Message {
	mi := &file_iap_iap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasketPosition.ProtoReflect.Descriptor instead.
func (*BasketPosition) Descriptor() ([]byte, []int) {
	return file_iap_iap_proto_rawDescGZIP(), []int{2}
}

func (x *BasketPosition) GetExtensionName() string {
	if x != nil {
		return x.ExtensionName
	}
	return ""
}

func (x *BasketPosition) GetInAppFeatureIdentifier() string {
	if x != nil {
		return x.InAppFeatureIdentifier
	}
	return ""
}

func (x *BasketPosition) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

func (x *BasketPosition) GetNetPrice() float64 {
	if x != nil {
		return x.NetPrice
	}
	return 0
}

func (x *BasketPosition) GetProratedNetPrice() float64 {
	if x != nil {
		return x.ProratedNetPrice
	}
	return 0
}

func (x *BasketPosition) GetTaxValue() float64 {
	if x != nil {
		return x.TaxValue
	}
	return 0
}

func (x *BasketPosition) GetGrossPrice() float64 {
	if x != nil {
		return x.GrossPrice
	}
	return 0
}

func (x *BasketPosition) GetTaxRate() float64 {
	if x != nil {
		return x.TaxRate
	}
	return 0
}

func (x *BasketPosition) GetSubscriptionChange() *SubscriptionChange {
	if x != nil {
		return x.SubscriptionChange
	}
	return nil
}

type SubscriptionChange struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	Type                          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	CurrentInAppFeatureIdentifier string                 `protobuf:"bytes,2,opt,name=current_in_app_feature_identifier,json=currentInAppFeatureIdentifier,proto3" json:"current_in_app_feature_identifier,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *SubscriptionChange) Reset() {
	*x = SubscriptionChange{}
	mi := &file_iap_iap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionChange) ProtoMessage() {}

func (x *SubscriptionChange) ProtoReflect() protoreflect.Message {
	mi := &file_iap_iap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionChange.ProtoReflect.Descriptor instead.
func (*SubscriptionChange) Descriptor() ([]byte, []int) {
	return file_iap_iap_proto_rawDescGZIP(), []int{3}
}

func (x *SubscriptionChange) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SubscriptionChange) GetCurrentInAppFeatureIdentifier() string {
	if x != nil {
		return x.CurrentInAppFeatureIdentifier
	}
	return ""
}

type PlaceOrderRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaxRate         float64                `protobuf:"fixed64,1,opt,name=tax_rate,json=taxRate,proto3" json:"tax_rate,omitempty"`
	Positions       []*BasketPosition      `protobuf:"bytes,2,rep,name=positions,proto3" json:"positions,omitempty"`
	Language        string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Domain          string                 `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	ShopwareVersion string                 `protobuf:"bytes,5,opt,name=shopware_version,json=shopwareVersion,proto3" json:"shopware_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlaceOrderRequest) Reset() {
	*x = PlaceOrderRequest{}
	mi := &file_iap_iap_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderRequest) ProtoMessage() {}

func (x *PlaceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iap_iap_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderRequest.ProtoReflect.Descriptor instead.
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return file_iap_iap_proto_rawDescGZIP(), []int{4}
}

func (x *PlaceOrderRequest) GetTaxRate() float64 {
	if x != nil {
		return x.TaxRate
	}
	return 0
}

func (x *PlaceOrderRequest) GetPositions() []*BasketPosition {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *PlaceOrderRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *PlaceOrderRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *PlaceOrderRequest) GetShopwareVersion() string {
	if x != nil {
		return x.ShopwareVersion
	}
	return ""
}

type PlaceOrderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Define fields based on successful order response, usually empty or confirmation
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderResponse) Reset() {
	*x = PlaceOrderResponse{}
	mi := &file_iap_iap_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderResponse) ProtoMessage() {}

func (x *PlaceOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iap_iap_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderResponse.ProtoReflect.Descriptor instead.
func (*PlaceOrderResponse) Descriptor() ([]byte, []int) {
	return file_iap_iap_proto_rawDescGZIP(), []int{5}
}

func (x *PlaceOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetInAppFeatureRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ExtensionName          string                 `protobuf:"bytes,1,opt,name=extension_name,json=extensionName,proto3" json:"extension_name,omitempty"`
	InAppFeatureIdentifier string                 `protobuf:"bytes,2,opt,name=in_app_feature_identifier,json=inAppFeatureIdentifier,proto3" json:"in_app_feature_identifier,omitempty"`
	Language               string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Domain                 string                 `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	ShopwareVersion        string                 `protobuf:"bytes,5,opt,name=shopware_version,json=shopwareVersion,proto3" json:"shopware_version,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetInAppFeatureRequest) Reset() {
	*x = GetInAppFeatureRequest{}
	mi := &file_iap_iap_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInAppFeatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInAppFeatureRequest) ProtoMessage() {}

func (x *GetInAppFeatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iap_iap_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInAppFeatureRequest.ProtoReflect.Descriptor instead.
func (*GetInAppFeatureRequest) Descriptor() ([]byte, []int) {
	return file_iap_iap_proto_rawDescGZIP(), []int{6}
}

func (x *GetInAppFeatureRequest) GetExtensionName() string {
	if x != nil {
		return x.ExtensionName
	}
	return ""
}

func (x *GetInAppFeatureRequest) GetInAppFeatureIdentifier() string {
	if x != nil {
		return x.InAppFeatureIdentifier
	}
	return ""
}

func (x *GetInAppFeatureRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *GetInAppFeatureRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *GetInAppFeatureRequest) GetShopwareVersion() string {
	if x != nil {
		return x.ShopwareVersion
	}
	return ""
}

type GetInAppFeatureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *structpb.Struct       `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInAppFeatureResponse) Reset() {
	*x = GetInAppFeatureResponse{}
	mi := &file_iap_iap_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInAppFeatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInAppFeatureResponse) ProtoMessage() {}

func (x *GetInAppFeatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iap_iap_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInAppFeatureResponse.ProtoReflect.Descriptor instead.
func (*GetInAppFeatureResponse) Descriptor() ([]byte, []int) {
	return file_iap_iap_proto_rawDescGZIP(), []int{7}
}

func (x *GetInAppFeatureResponse) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

type GetInAppPlansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExtensionName string                 `protobuf:"bytes,1,opt,name=extension_name,json=extensionName,proto3" json:"extension_name,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInAppPlansRequest) Reset() {
	*x = GetInAppPlansRequest{}
	mi := &file_iap_iap_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInAppPlansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInAppPlansRequest) ProtoMessage() {}

func (x *GetInAppPlansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iap_iap_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInAppPlansRequest.ProtoReflect.Descriptor instead.
func (*GetInAppPlansRequest) Descriptor() ([]byte, []int) {
	return file_iap_iap_proto_rawDescGZIP(), []int{8}
}

func (x *GetInAppPlansRequest) GetExtensionName() string {
	if x != nil {
		return x.ExtensionName
	}
	return ""
}

func (x *GetInAppPlansRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type GetInAppPlansResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plans         []*InAppPlan           `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInAppPlansResponse) Reset() {
	*x = GetInAppPlansResponse{}
	mi := &file_iap_iap_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInAppPlansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInAppPlansResponse) ProtoMessage() {}

func (x *GetInAppPlansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iap_iap_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInAppPlansResponse.ProtoReflect.Descriptor instead.
func (*GetInAppPlansResponse) Descriptor() ([]byte, []int) {
	return file_iap_iap_proto_rawDescGZIP(), []int{9}
}

func (x *GetInAppPlansResponse) GetPlans() []*InAppPlan {
	if x != nil {
		return x.Plans
	}
	return nil
}

type InAppPlan struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Identifier        string                 `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ServiceConditions *string                `protobuf:"bytes,5,opt,name=service_conditions,json=serviceConditions,proto3,oneof" json:"service_conditions,omitempty"`
	WebsiteGtc        *string                `protobuf:"bytes,6,opt,name=website_gtc,json=websiteGtc,proto3,oneof" json:"website_gtc,omitempty"`
	PriceModels       []*PriceModel          `protobuf:"bytes,7,rep,name=price_models,json=priceModels,proto3" json:"price_models,omitempty"`
	PriceModel        *PriceModel            `protobuf:"bytes,8,opt,name=price_model,json=priceModel,proto3" json:"price_model,omitempty"`
	Group             *PlanGroup             `protobuf:"bytes,9,opt,name=group,proto3" json:"group,omitempty"`
	Status            string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InAppPlan) Reset() {
	*x = InAppPlan{}
	mi := &file_iap_iap_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InAppPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InAppPlan) ProtoMessage() {}

func (x *InAppPlan) ProtoReflect() protoreflect.Message {
	mi := &file_iap_iap_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InAppPlan.ProtoReflect.Descriptor instead.
func (*InAppPlan) Descriptor() ([]byte, []int) {
	return file_iap_iap_proto_rawDescGZIP(), []int{10}
}

func (x *InAppPlan) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InAppPlan) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *InAppPlan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InAppPlan) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InAppPlan) GetServiceConditions() string {
	if x != nil && x.ServiceConditions != nil {
		return *x.ServiceConditions
	}
	return ""
}

func (x *InAppPlan) GetWebsiteGtc() string {
	if x != nil && x.WebsiteGtc != nil {
		return *x.WebsiteGtc
	}
	return ""
}

func (x *InAppPlan) GetPriceModels() []*PriceModel {
	if x != nil {
		return x.PriceModels
	}
	return nil
}

func (x *InAppPlan) GetPriceModel() *PriceModel {
	if x != nil {
		return x.PriceModel
	}
	return nil
}

func (x *InAppPlan) GetGroup() *PlanGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *InAppPlan) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PriceModel struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Variant        string                 `protobuf:"bytes,1,opt,name=variant,proto3" json:"variant,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Price          float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	ConditionsType *string                `protobuf:"bytes,4,opt,name=conditions_type,json=conditionsType,proto3,oneof" json:"conditions_type,omitempty"`
	Duration       int32                  `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`
	OneTimeOnly    *bool                  `protobuf:"varint,6,opt,name=one_time_only,json=oneTimeOnly,proto3,oneof" json:"one_time_only,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PriceModel) Reset() {
	*x = PriceModel{}
	mi := &file_iap_iap_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceModel) ProtoMessage() {}

func (x *PriceModel) ProtoReflect() protoreflect.Message {
	mi := &file_iap_iap_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceModel.ProtoReflect.Descriptor instead.
func (*PriceModel) Descriptor() ([]byte, []int) {
	return file_iap_iap_proto_rawDescGZIP(), []int{11}
}

func (x *PriceModel) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

func (x *PriceModel) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PriceModel) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PriceModel) GetConditionsType() string {
	if x != nil && x.ConditionsType != nil {
		return *x.ConditionsType
	}
	return ""
}

func (x *PriceModel) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *PriceModel) GetOneTimeOnly() bool {
	if x != nil && x.OneTimeOnly != nil {
		return *x.OneTimeOnly
	}
	return false
}

type PlanGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanGroup) Reset() {
	*x = PlanGroup{}
	mi := &file_iap_iap_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanGroup) ProtoMessage() {}

func (x *PlanGroup) ProtoReflect() protoreflect.Message {
	mi := &file_iap_iap_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanGroup.ProtoReflect.Descriptor instead.
func (*PlanGroup) Descriptor() ([]byte, []int) {
	return file_iap_iap_proto_rawDescGZIP(), []int{12}
}

func (x *PlanGroup) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *PlanGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_iap_iap_proto protoreflect.FileDescriptor

const file_iap_iap_proto_rawDesc = "" +
	"\n" +
	"\riap/iap.proto\x12\x03iap\x1a\x1cgoogle/protobuf/struct.proto\x1a\x14common/options.proto\"\xf3\x01\n" +
	"\x16CalculateBasketRequest\x12%\n" +
	"\x0eextension_name\x18\x01 \x01(\tR\rextensionName\x129\n" +
	"\x19in_app_feature_identifier\x18\x02 \x01(\tR\x16inAppFeatureIdentifier\x12\x18\n" +
	"\avariant\x18\x03 \x01(\tR\avariant\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x16\n" +
	"\x06domain\x18\x05 \x01(\tR\x06domain\x12)\n" +
	"\x10shopware_version\x18\x06 \x01(\tR\x0fshopwareVersion\"g\n" +
	"\x17CalculateBasketResponse\x12\x19\n" +
	"\btax_rate\x18\x01 \x01(\x01R\ataxRate\x121\n" +
	"\tpositions\x18\x02 \x03(\v2\x13.iap.BasketPositionR\tpositions\"\x97\x03\n" +
	"\x0eBasketPosition\x12%\n" +
	"\x0eextension_name\x18\x01 \x01(\tR\rextensionName\x129\n" +
	"\x19in_app_feature_identifier\x18\x02 \x01(\tR\x16inAppFeatureIdentifier\x12\x18\n" +
	"\avariant\x18\x03 \x01(\tR\avariant\x12\x1b\n" +
	"\tnet_price\x18\x04 \x01(\x01R\bnetPrice\x12,\n" +
	"\x12prorated_net_price\x18\x05 \x01(\x01R\x10proratedNetPrice\x12\x1b\n" +
	"\ttax_value\x18\x06 \x01(\x01R\btaxValue\x12\x1f\n" +
	"\vgross_price\x18\a \x01(\x01R\n" +
	"grossPrice\x12\x19\n" +
	"\btax_rate\x18\b \x01(\x01R\ataxRate\x12M\n" +
	"\x13subscription_change\x18\t \x01(\v2\x17.iap.SubscriptionChangeH\x00R\x12subscriptionChange\x88\x01\x01B\x16\n" +
	"\x14_subscription_change\"r\n" +
	"\x12SubscriptionChange\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12H\n" +
	"!current_in_app_feature_identifier\x18\x02 \x01(\tR\x1dcurrentInAppFeatureIdentifier\"\xc0\x01\n" +
	"\x11PlaceOrderRequest\x12\x19\n" +
	"\btax_rate\x18\x01 \x01(\x01R\ataxRate\x121\n" +
	"\tpositions\x18\x02 \x03(\v2\x13.iap.BasketPositionR\tpositions\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\x12)\n" +
	"\x10shopware_version\x18\x05 \x01(\tR\x0fshopwareVersion\".\n" +
	"\x12PlaceOrderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xd9\x01\n" +
	"\x16GetInAppFeatureRequest\x12%\n" +
	"\x0eextension_name\x18\x01 \x01(\tR\rextensionName\x129\n" +
	"\x19in_app_feature_identifier\x18\x02 \x01(\tR\x16inAppFeatureIdentifier\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\x12)\n" +
	"\x10shopware_version\x18\x05 \x01(\tR\x0fshopwareVersion\"L\n" +
	"\x17GetInAppFeatureResponse\x121\n" +
	"\apayload\x18\x01 \x01(\v2\x17.google.protobuf.StructR\apayload\"Y\n" +
	"\x14GetInAppPlansRequest\x12%\n" +
	"\x0eextension_name\x18\x01 \x01(\tR\rextensionName\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\"=\n" +
	"\x15GetInAppPlansResponse\x12$\n" +
	"\x05plans\x18\x01 \x03(\v2\x0e.iap.InAppPlanR\x05plans\"\x96\x03\n" +
	"\tInAppPlan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x122\n" +
	"\x12service_conditions\x18\x05 \x01(\tH\x00R\x11serviceConditions\x88\x01\x01\x12$\n" +
	"\vwebsite_gtc\x18\x06 \x01(\tH\x01R\n" +
	"websiteGtc\x88\x01\x01\x122\n" +
	"\fprice_models\x18\a \x03(\v2\x0f.iap.PriceModelR\vpriceModels\x120\n" +
	"\vprice_model\x18\b \x01(\v2\x0f.iap.PriceModelR\n" +
	"priceModel\x12$\n" +
	"\x05group\x18\t \x01(\v2\x0e.iap.PlanGroupR\x05group\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06statusB\x15\n" +
	"\x13_service_conditionsB\x0e\n" +
	"\f_website_gtc\"\xe9\x01\n" +
	"\n" +
	"PriceModel\x12\x18\n" +
	"\avariant\x18\x01 \x01(\tR\avariant\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12,\n" +
	"\x0fconditions_type\x18\x04 \x01(\tH\x00R\x0econditionsType\x88\x01\x01\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x05R\bduration\x12'\n" +
	"\rone_time_only\x18\x06 \x01(\bH\x01R\voneTimeOnly\x88\x01\x01B\x12\n" +
	"\x10_conditions_typeB\x10\n" +
	"\x0e_one_time_only\"?\n" +
	"\tPlanGroup\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\xe0\x05\n" +
	"\n" +
	"IAPService\x12L\n" +
	"\x0fCalculateBasket\x12\x1b.iap.CalculateBasketRequest\x1a\x1c.iap.CalculateBasketResponse\x12=\n" +
	"\n" +
	"PlaceOrder\x12\x16.iap.PlaceOrderRequest\x1a\x17.iap.PlaceOrderResponse\x12L\n" +
	"\x0fGetInAppFeature\x12\x1b.iap.GetInAppFeatureRequest\x1a\x1c.iap.GetInAppFeatureResponse\x12\xff\x01\n" +
	"\rGetInAppPlans\x12\x19.iap.GetInAppPlansRequest\x1a\x1a.iap.GetInAppPlansResponse\"\xb6\x01\x92\xb5\x18@\n" +
	"\rauthorization\x1a/Not required - uses internal M2M authentication\x92\xb5\x18n\n" +
	"\x11x-request-service\x10\x01\x1a@Service name making the request for tracking and log correlation\"\x15SwagPurchaseInterface\x1a\xf4\x01\x8a\xb5\x18x\n" +
	"\rauthorization\x10\x01\x1a5OAuth access token (with or without 'Bearer ' prefix)\".Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9...\x8a\xb5\x18t\n" +
	"\fx-request-id\x1a>Request tracing ID for distributed tracing and log correlation\"$550e8400-e29b-41d4-a716-446655440000Bs\n" +
	"\acom.iapB\bIapProtoP\x01Z2github.com/shopware/transaction-gateway-protos/iap\xa2\x02\x03IXX\xaa\x02\x03Iap\xca\x02\x03Iap\xe2\x02\x0fIap\\GPBMetadata\xea\x02\x03Iapb\x06proto3"

var (
	file_iap_iap_proto_rawDescOnce sync.Once
	file_iap_iap_proto_rawDescData []byte
)

func file_iap_iap_proto_rawDescGZIP() []byte {
	file_iap_iap_proto_rawDescOnce.Do(func() {
		file_iap_iap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iap_iap_proto_rawDesc), len(file_iap_iap_proto_rawDesc)))
	})
	return file_iap_iap_proto_rawDescData
}

var file_iap_iap_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_iap_iap_proto_goTypes = []any{
	(*CalculateBasketRequest)(nil),  // 0: iap.CalculateBasketRequest
	(*CalculateBasketResponse)(nil), // 1: iap.CalculateBasketResponse
	(*BasketPosition)(nil),          // 2: iap.BasketPosition
	(*SubscriptionChange)(nil),      // 3: iap.SubscriptionChange
	(*PlaceOrderRequest)(nil),       // 4: iap.PlaceOrderRequest
	(*PlaceOrderResponse)(nil),      // 5: iap.PlaceOrderResponse
	(*GetInAppFeatureRequest)(nil),  // 6: iap.GetInAppFeatureRequest
	(*GetInAppFeatureResponse)(nil), // 7: iap.GetInAppFeatureResponse
	(*GetInAppPlansRequest)(nil),    // 8: iap.GetInAppPlansRequest
	(*GetInAppPlansResponse)(nil),   // 9: iap.GetInAppPlansResponse
	(*InAppPlan)(nil),               // 10: iap.InAppPlan
	(*PriceModel)(nil),              // 11: iap.PriceModel
	(*PlanGroup)(nil),               // 12: iap.PlanGroup
	(*structpb.Struct)(nil),         // 13: google.protobuf.Struct
}
var file_iap_iap_proto_depIdxs = []int32{
	2,  // 0: iap.CalculateBasketResponse.positions:type_name -> iap.BasketPosition
	3,  // 1: iap.BasketPosition.subscription_change:type_name -> iap.SubscriptionChange
	2,  // 2: iap.PlaceOrderRequest.positions:type_name -> iap.BasketPosition
	13, // 3: iap.GetInAppFeatureResponse.payload:type_name -> google.protobuf.Struct
	10, // 4: iap.GetInAppPlansResponse.plans:type_name -> iap.InAppPlan
	11, // 5: iap.InAppPlan.price_models:type_name -> iap.PriceModel
	11, // 6: iap.InAppPlan.price_model:type_name -> iap.PriceModel
	12, // 7: iap.InAppPlan.group:type_name -> iap.PlanGroup
	0,  // 8: iap.IAPService.CalculateBasket:input_type -> iap.CalculateBasketRequest
	4,  // 9: iap.IAPService.PlaceOrder:input_type -> iap.PlaceOrderRequest
	6,  // 10: iap.IAPService.GetInAppFeature:input_type -> iap.GetInAppFeatureRequest
	8,  // 11: iap.IAPService.GetInAppPlans:input_type -> iap.GetInAppPlansRequest
	1,  // 12: iap.IAPService.CalculateBasket:output_type -> iap.CalculateBasketResponse
	5,  // 13: iap.IAPService.PlaceOrder:output_type -> iap.PlaceOrderResponse
	7,  // 14: iap.IAPService.GetInAppFeature:output_type -> iap.GetInAppFeatureResponse
	9,  // 15: iap.IAPService.GetInAppPlans:output_type -> iap.GetInAppPlansResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_iap_iap_proto_init() }
func file_iap_iap_proto_init() {
	if File_iap_iap_proto != nil {
		return
	}
	file_iap_iap_proto_msgTypes[2].OneofWrappers = []any{}
	file_iap_iap_proto_msgTypes[10].OneofWrappers = []any{}
	file_iap_iap_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iap_iap_proto_rawDesc), len(file_iap_iap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iap_iap_proto_goTypes,
		DependencyIndexes: file_iap_iap_proto_depIdxs,
		MessageInfos:      file_iap_iap_proto_msgTypes,
	}.Build()
	File_iap_iap_proto = out.File
	file_iap_iap_proto_goTypes = nil
	file_iap_iap_proto_depIdxs = nil
}
