<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: iap/iap.proto

namespace Iap;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>iap.PriceModel</code>
 */
class PriceModel extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string variant = 1 [json_name = "variant"];</code>
     */
    protected $variant = '';
    /**
     * Generated from protobuf field <code>string type = 2 [json_name = "type"];</code>
     */
    protected $type = '';
    /**
     * Generated from protobuf field <code>double price = 3 [json_name = "price"];</code>
     */
    protected $price = 0.0;
    /**
     * Generated from protobuf field <code>optional string conditions_type = 4 [json_name = "conditionsType"];</code>
     */
    protected $conditions_type = null;
    /**
     * Generated from protobuf field <code>int32 duration = 5 [json_name = "duration"];</code>
     */
    protected $duration = 0;
    /**
     * Generated from protobuf field <code>optional bool one_time_only = 6 [json_name = "oneTimeOnly"];</code>
     */
    protected $one_time_only = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $variant
     *     @type string $type
     *     @type float $price
     *     @type string $conditions_type
     *     @type int $duration
     *     @type bool $one_time_only
     * }
     */
    public function __construct($data = NULL) {
        \Iap\GPBMetadata\Iap::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string variant = 1 [json_name = "variant"];</code>
     * @return string
     */
    public function getVariant()
    {
        return $this->variant;
    }

    /**
     * Generated from protobuf field <code>string variant = 1 [json_name = "variant"];</code>
     * @param string $var
     * @return $this
     */
    public function setVariant($var)
    {
        GPBUtil::checkString($var, True);
        $this->variant = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string type = 2 [json_name = "type"];</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 2 [json_name = "type"];</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double price = 3 [json_name = "price"];</code>
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>double price = 3 [json_name = "price"];</code>
     * @param float $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string conditions_type = 4 [json_name = "conditionsType"];</code>
     * @return string
     */
    public function getConditionsType()
    {
        return isset($this->conditions_type) ? $this->conditions_type : '';
    }

    public function hasConditionsType()
    {
        return isset($this->conditions_type);
    }

    public function clearConditionsType()
    {
        unset($this->conditions_type);
    }

    /**
     * Generated from protobuf field <code>optional string conditions_type = 4 [json_name = "conditionsType"];</code>
     * @param string $var
     * @return $this
     */
    public function setConditionsType($var)
    {
        GPBUtil::checkString($var, True);
        $this->conditions_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 duration = 5 [json_name = "duration"];</code>
     * @return int
     */
    public function getDuration()
    {
        return $this->duration;
    }

    /**
     * Generated from protobuf field <code>int32 duration = 5 [json_name = "duration"];</code>
     * @param int $var
     * @return $this
     */
    public function setDuration($var)
    {
        GPBUtil::checkInt32($var);
        $this->duration = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool one_time_only = 6 [json_name = "oneTimeOnly"];</code>
     * @return bool
     */
    public function getOneTimeOnly()
    {
        return isset($this->one_time_only) ? $this->one_time_only : false;
    }

    public function hasOneTimeOnly()
    {
        return isset($this->one_time_only);
    }

    public function clearOneTimeOnly()
    {
        unset($this->one_time_only);
    }

    /**
     * Generated from protobuf field <code>optional bool one_time_only = 6 [json_name = "oneTimeOnly"];</code>
     * @param bool $var
     * @return $this
     */
    public function setOneTimeOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->one_time_only = $var;

        return $this;
    }

}

