<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth/auth.proto

namespace Auth\GPBMetadata;

class Auth
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Struct::initOnce();
        \Common\GPBMetadata\Options::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xC3\x08\x0A\x0Fauth/auth.proto\x12\x04auth\x1A\x14common/options.proto\"g\x0A\x13ExchangeCodeRequest\x12-\x0A\x12authorization_code\x18\x01 \x01(\x09R\x11authorizationCode\x12!\x0A\x0Credirect_uri\x18\x02 \x01(\x09R\x0BredirectUri\"}\x0A\x14ExchangeCodeResponse\x12!\x0A\x0Caccess_token\x18\x01 \x01(\x09R\x0BaccessToken\x12#\x0A\x0Drefresh_token\x18\x02 \x01(\x09R\x0CrefreshToken\x12\x1D\x0A\x0Aexpires_in\x18\x03 \x01(\x03R\x09expiresIn\":\x0A\x13RefreshTokenRequest\x12#\x0A\x0Drefresh_token\x18\x01 \x01(\x09R\x0CrefreshToken\"}\x0A\x14RefreshTokenResponse\x12!\x0A\x0Caccess_token\x18\x01 \x01(\x09R\x0BaccessToken\x12#\x0A\x0Drefresh_token\x18\x02 \x01(\x09R\x0CrefreshToken\x12\x1D\x0A\x0Aexpires_in\x18\x03 \x01(\x03R\x09expiresIn\":\x0A\x15GetUserAccountRequest\x12!\x0A\x0Caccess_token\x18\x01 \x01(\x09R\x0BaccessToken\"E\x0A\x16GetUserAccountResponse\x12+\x0A\x04user\x18\x01 \x01(\x0B2\x17.google.protobuf.StructR\x04user2\xE2\x02\x0A\x0BAuthService\x12E\x0A\x0CExchangeCode\x12\x19.auth.ExchangeCodeRequest\x1A\x1A.auth.ExchangeCodeResponse\x12E\x0A\x0CRefreshToken\x12\x19.auth.RefreshTokenRequest\x1A\x1A.auth.RefreshTokenResponse\x12K\x0A\x0EGetUserAccount\x12\x1B.auth.GetUserAccountRequest\x1A\x1C.auth.GetUserAccountResponse\x1Ax\x8A\xB5\x18t\x0A\x0Cx-request-id\x1A>Request tracing ID for distributed tracing and log correlation\"\$550e8400-e29b-41d4-a716-446655440000B\x80\x01\x0A\x08com.authB\x09AuthProtoP\x01Z9github.com/shopware/transaction-gateway/pkg/proto/go/auth\xA2\x02\x03AXX\xAA\x02\x04Auth\xCA\x02\x04Auth\xE2\x02\x10Auth\\GPBMetadata\xEA\x02\x04Authb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

