<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth/auth.proto

namespace Auth;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>auth.ExchangeCodeRequest</code>
 */
class ExchangeCodeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string authorization_code = 1 [json_name = "authorizationCode"];</code>
     */
    protected $authorization_code = '';
    /**
     * Client's redirect URI used in OAuth flow
     *
     * Generated from protobuf field <code>string redirect_uri = 2 [json_name = "redirectUri"];</code>
     */
    protected $redirect_uri = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $authorization_code
     *     @type string $redirect_uri
     *           Client's redirect URI used in OAuth flow
     * }
     */
    public function __construct($data = NULL) {
        \Auth\GPBMetadata\Auth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string authorization_code = 1 [json_name = "authorizationCode"];</code>
     * @return string
     */
    public function getAuthorizationCode()
    {
        return $this->authorization_code;
    }

    /**
     * Generated from protobuf field <code>string authorization_code = 1 [json_name = "authorizationCode"];</code>
     * @param string $var
     * @return $this
     */
    public function setAuthorizationCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->authorization_code = $var;

        return $this;
    }

    /**
     * Client's redirect URI used in OAuth flow
     *
     * Generated from protobuf field <code>string redirect_uri = 2 [json_name = "redirectUri"];</code>
     * @return string
     */
    public function getRedirectUri()
    {
        return $this->redirect_uri;
    }

    /**
     * Client's redirect URI used in OAuth flow
     *
     * Generated from protobuf field <code>string redirect_uri = 2 [json_name = "redirectUri"];</code>
     * @param string $var
     * @return $this
     */
    public function setRedirectUri($var)
    {
        GPBUtil::checkString($var, True);
        $this->redirect_uri = $var;

        return $this;
    }

}

