<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth/auth.proto

namespace Auth;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>auth.GetTokenForSessionResponse</code>
 */
class GetTokenForSessionResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string access_token = 1 [json_name = "accessToken"];</code>
     */
    protected $access_token = '';
    /**
     * Generated from protobuf field <code>int64 expires_in = 2 [json_name = "expiresIn"];</code>
     */
    protected $expires_in = 0;
    /**
     * Generated from protobuf field <code>bool session_found = 3 [json_name = "sessionFound"];</code>
     */
    protected $session_found = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $access_token
     *     @type int|string $expires_in
     *     @type bool $session_found
     * }
     */
    public function __construct($data = NULL) {
        \Auth\GPBMetadata\Auth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string access_token = 1 [json_name = "accessToken"];</code>
     * @return string
     */
    public function getAccessToken()
    {
        return $this->access_token;
    }

    /**
     * Generated from protobuf field <code>string access_token = 1 [json_name = "accessToken"];</code>
     * @param string $var
     * @return $this
     */
    public function setAccessToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->access_token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 expires_in = 2 [json_name = "expiresIn"];</code>
     * @return int|string
     */
    public function getExpiresIn()
    {
        return $this->expires_in;
    }

    /**
     * Generated from protobuf field <code>int64 expires_in = 2 [json_name = "expiresIn"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpiresIn($var)
    {
        GPBUtil::checkInt64($var);
        $this->expires_in = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool session_found = 3 [json_name = "sessionFound"];</code>
     * @return bool
     */
    public function getSessionFound()
    {
        return $this->session_found;
    }

    /**
     * Generated from protobuf field <code>bool session_found = 3 [json_name = "sessionFound"];</code>
     * @param bool $var
     * @return $this
     */
    public function setSessionFound($var)
    {
        GPBUtil::checkBool($var);
        $this->session_found = $var;

        return $this;
    }

}

