<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: purchases/purchases.proto

namespace Purchases\GPBMetadata;

class Purchases
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Common\GPBMetadata\Options::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xA8\x07\x0A\x19purchases/purchases.proto\x12\x09purchases\"5\x0A\x1BGetPurchasesByDomainRequest\x12\x16\x0A\x06domain\x18\x01 \x01(\x09R\x06domain\"Q\x0A\x1CGetPurchasesByDomainResponse\x121\x0A\x09purchases\x18\x01 \x03(\x0B2\x13.purchases.PurchaseR\x09purchases\"\xFB\x01\x0A\x08Purchase\x12\x1F\x0A\x0Bplugin_name\x18\x01 \x01(\x09R\x0ApluginName\x12\x1E\x0A\x0Aidentifier\x18\x02 \x01(\x09R\x0Aidentifier\x12*\x0A\x11next_booking_date\x18\x03 \x01(\x09R\x0FnextBookingDate\x12\x1A\x0A\x08quantity\x18\x04 \x01(\x05R\x08quantity\x12E\x0A\x1Cpending_downgrade_identifier\x18\x05 \x01(\x09H\x00R\x1ApendingDowngradeIdentifier\x88\x01\x01B\x1F\x0A\x1D_pending_downgrade_identifier2\xCF\x02\x0A\x10PurchasesService\x12g\x0A\x14GetPurchasesByDomain\x12&.purchases.GetPurchasesByDomainRequest\x1A'.purchases.GetPurchasesByDomainResponse\x1A\xD1\x01\x8A\xB5\x18t\x0A\x0Cx-request-id\x1A>Request tracing ID for distributed tracing and log correlation\"\$550e8400-e29b-41d4-a716-446655440000\x8A\xB5\x18U\x0A\x11x-request-service\x10\x01\x1A(Request service name for log correlation\"\x14swag-copilot-serviceB\x9D\x01\x0A\x0Dcom.purchasesB\x0EPurchasesProtoP\x01Z8github.com/shopware/transaction-gateway-protos/purchases\xA2\x02\x03PXX\xAA\x02\x09Purchases\xCA\x02\x09Purchases\xE2\x02\x15Purchases\\GPBMetadata\xEA\x02\x09Purchasesb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

