<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth/v1/auth.proto

namespace Transaction\Auth\V1\GPBMetadata;

class Auth
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Struct::initOnce();
        \Common\GPBMetadata\Options::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x80\x0A\x0A\x12auth/v1/auth.proto\x12\x13transaction.auth.v1\x1A\x14common/options.proto\"g\x0A\x13ExchangeCodeRequest\x12-\x0A\x12authorization_code\x18\x01 \x01(\x09R\x11authorizationCode\x12!\x0A\x0Credirect_uri\x18\x02 \x01(\x09R\x0BredirectUri\"}\x0A\x14ExchangeCodeResponse\x12!\x0A\x0Caccess_token\x18\x01 \x01(\x09R\x0BaccessToken\x12#\x0A\x0Drefresh_token\x18\x02 \x01(\x09R\x0CrefreshToken\x12\x1D\x0A\x0Aexpires_in\x18\x03 \x01(\x03R\x09expiresIn\":\x0A\x13RefreshTokenRequest\x12#\x0A\x0Drefresh_token\x18\x01 \x01(\x09R\x0CrefreshToken\"}\x0A\x14RefreshTokenResponse\x12!\x0A\x0Caccess_token\x18\x01 \x01(\x09R\x0BaccessToken\x12#\x0A\x0Drefresh_token\x18\x02 \x01(\x09R\x0CrefreshToken\x12\x1D\x0A\x0Aexpires_in\x18\x03 \x01(\x03R\x09expiresIn\":\x0A\x15GetUserAccountRequest\x12!\x0A\x0Caccess_token\x18\x01 \x01(\x09R\x0BaccessToken\"E\x0A\x16GetUserAccountResponse\x12+\x0A\x04user\x18\x01 \x01(\x0B2\x17.google.protobuf.StructR\x04user2\xBC\x03\x0A\x0BAuthService\x12c\x0A\x0CExchangeCode\x12(.transaction.auth.v1.ExchangeCodeRequest\x1A).transaction.auth.v1.ExchangeCodeResponse\x12c\x0A\x0CRefreshToken\x12(.transaction.auth.v1.RefreshTokenRequest\x1A).transaction.auth.v1.RefreshTokenResponse\x12i\x0A\x0EGetUserAccount\x12*.transaction.auth.v1.GetUserAccountRequest\x1A+.transaction.auth.v1.GetUserAccountResponse\x1Ax\x8A\xB5\x18t\x0A\x0Cx-request-id\x1A>Request tracing ID for distributed tracing and log correlation\"\$550e8400-e29b-41d4-a716-446655440000B\xD1\x01\x0A\x17com.transaction.auth.v1B\x09AuthProtoP\x01Z=github.com/shopware/transaction-gateway-protos/auth/v1;authv1\xA2\x02\x03TAX\xAA\x02\x13Transaction.Auth.V1\xCA\x02\x13Transaction\\Auth\\V1\xE2\x02\x1FTransaction\\Auth\\V1\\GPBMetadata\xEA\x02\x15Transaction::Auth::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

