<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: purchases/v1/purchases.proto

namespace Transaction\Purchases\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Purchase represents a single purchase/subscription record
 *
 * Generated from protobuf message <code>transaction.purchases.v1.Purchase</code>
 */
class Purchase extends \Google\Protobuf\Internal\Message
{
    /**
     * Name of the purchased plugin/extension
     *
     * Generated from protobuf field <code>string plugin_name = 1 [json_name = "pluginName"];</code>
     */
    protected $plugin_name = '';
    /**
     * Unique identifier for the purchase variant (e.g., "SwagCommercialBasic-1m")
     *
     * Generated from protobuf field <code>string identifier = 2 [json_name = "identifier"];</code>
     */
    protected $identifier = '';
    /**
     * Next billing date in ISO 8601 format (e.g., "2025-01-15")
     *
     * Generated from protobuf field <code>string next_booking_date = 3 [json_name = "nextBookingDate"];</code>
     */
    protected $next_booking_date = '';
    /**
     * Quantity of licenses purchased
     *
     * Generated from protobuf field <code>int32 quantity = 4 [json_name = "quantity"];</code>
     */
    protected $quantity = 0;
    /**
     * Identifier of pending downgrade, if any (null if no pending downgrade)
     *
     * Generated from protobuf field <code>optional string pending_downgrade_identifier = 5 [json_name = "pendingDowngradeIdentifier"];</code>
     */
    protected $pending_downgrade_identifier = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $plugin_name
     *           Name of the purchased plugin/extension
     *     @type string $identifier
     *           Unique identifier for the purchase variant (e.g., "SwagCommercialBasic-1m")
     *     @type string $next_booking_date
     *           Next billing date in ISO 8601 format (e.g., "2025-01-15")
     *     @type int $quantity
     *           Quantity of licenses purchased
     *     @type string $pending_downgrade_identifier
     *           Identifier of pending downgrade, if any (null if no pending downgrade)
     * }
     */
    public function __construct($data = NULL) {
        \Transaction\Purchases\V1\GPBMetadata\Purchases::initOnce();
        parent::__construct($data);
    }

    /**
     * Name of the purchased plugin/extension
     *
     * Generated from protobuf field <code>string plugin_name = 1 [json_name = "pluginName"];</code>
     * @return string
     */
    public function getPluginName()
    {
        return $this->plugin_name;
    }

    /**
     * Name of the purchased plugin/extension
     *
     * Generated from protobuf field <code>string plugin_name = 1 [json_name = "pluginName"];</code>
     * @param string $var
     * @return $this
     */
    public function setPluginName($var)
    {
        GPBUtil::checkString($var, True);
        $this->plugin_name = $var;

        return $this;
    }

    /**
     * Unique identifier for the purchase variant (e.g., "SwagCommercialBasic-1m")
     *
     * Generated from protobuf field <code>string identifier = 2 [json_name = "identifier"];</code>
     * @return string
     */
    public function getIdentifier()
    {
        return $this->identifier;
    }

    /**
     * Unique identifier for the purchase variant (e.g., "SwagCommercialBasic-1m")
     *
     * Generated from protobuf field <code>string identifier = 2 [json_name = "identifier"];</code>
     * @param string $var
     * @return $this
     */
    public function setIdentifier($var)
    {
        GPBUtil::checkString($var, True);
        $this->identifier = $var;

        return $this;
    }

    /**
     * Next billing date in ISO 8601 format (e.g., "2025-01-15")
     *
     * Generated from protobuf field <code>string next_booking_date = 3 [json_name = "nextBookingDate"];</code>
     * @return string
     */
    public function getNextBookingDate()
    {
        return $this->next_booking_date;
    }

    /**
     * Next billing date in ISO 8601 format (e.g., "2025-01-15")
     *
     * Generated from protobuf field <code>string next_booking_date = 3 [json_name = "nextBookingDate"];</code>
     * @param string $var
     * @return $this
     */
    public function setNextBookingDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_booking_date = $var;

        return $this;
    }

    /**
     * Quantity of licenses purchased
     *
     * Generated from protobuf field <code>int32 quantity = 4 [json_name = "quantity"];</code>
     * @return int
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Quantity of licenses purchased
     *
     * Generated from protobuf field <code>int32 quantity = 4 [json_name = "quantity"];</code>
     * @param int $var
     * @return $this
     */
    public function setQuantity($var)
    {
        GPBUtil::checkInt32($var);
        $this->quantity = $var;

        return $this;
    }

    /**
     * Identifier of pending downgrade, if any (null if no pending downgrade)
     *
     * Generated from protobuf field <code>optional string pending_downgrade_identifier = 5 [json_name = "pendingDowngradeIdentifier"];</code>
     * @return string
     */
    public function getPendingDowngradeIdentifier()
    {
        return isset($this->pending_downgrade_identifier) ? $this->pending_downgrade_identifier : '';
    }

    public function hasPendingDowngradeIdentifier()
    {
        return isset($this->pending_downgrade_identifier);
    }

    public function clearPendingDowngradeIdentifier()
    {
        unset($this->pending_downgrade_identifier);
    }

    /**
     * Identifier of pending downgrade, if any (null if no pending downgrade)
     *
     * Generated from protobuf field <code>optional string pending_downgrade_identifier = 5 [json_name = "pendingDowngradeIdentifier"];</code>
     * @param string $var
     * @return $this
     */
    public function setPendingDowngradeIdentifier($var)
    {
        GPBUtil::checkString($var, True);
        $this->pending_downgrade_identifier = $var;

        return $this;
    }

}

