<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/options.proto

namespace Common\GPBMetadata;

class Options
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xD2\x02\x0A\x14common/options.proto\x12\x06common\x1A google/protobuf/descriptor.proto\"|\x0A\x0EMetadataHeader\x12\x12\x0A\x04name\x18\x01 \x01(\x09R\x04name\x12\x1A\x0A\x08required\x18\x02 \x01(\x08R\x08required\x12 \x0A\x0Bdescription\x18\x03 \x01(\x09R\x0Bdescription\x12\x18\x0A\x07example\x18\x04 \x01(\x09R\x07exampleB\x89\x01\x0A\x0Acom.commonB\x0COptionsProtoP\x01Z5github.com/shopware/transaction-gateway-protos/common\xA2\x02\x03CXX\xAA\x02\x06Common\xCA\x02\x06Common\xE2\x02\x12Common\\GPBMetadata\xEA\x02\x06Commonb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

