<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: purchases/purchases.proto

namespace Purchases;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * GetPurchasesByDomainRequest is the request message for GetPurchasesByDomain RPC
 *
 * Generated from protobuf message <code>purchases.GetPurchasesByDomainRequest</code>
 */
class GetPurchasesByDomainRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The shop domain to query purchases for (e.g., "sw9.service.com")
     *
     * Generated from protobuf field <code>string domain = 1 [json_name = "domain"];</code>
     */
    protected $domain = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $domain
     *           The shop domain to query purchases for (e.g., "sw9.service.com")
     * }
     */
    public function __construct($data = NULL) {
        \Purchases\GPBMetadata\Purchases::initOnce();
        parent::__construct($data);
    }

    /**
     * The shop domain to query purchases for (e.g., "sw9.service.com")
     *
     * Generated from protobuf field <code>string domain = 1 [json_name = "domain"];</code>
     * @return string
     */
    public function getDomain()
    {
        return $this->domain;
    }

    /**
     * The shop domain to query purchases for (e.g., "sw9.service.com")
     *
     * Generated from protobuf field <code>string domain = 1 [json_name = "domain"];</code>
     * @param string $var
     * @return $this
     */
    public function setDomain($var)
    {
        GPBUtil::checkString($var, True);
        $this->domain = $var;

        return $this;
    }

}

