<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: purchases/purchases.proto

namespace Purchases;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * GetPurchasesByDomainResponse is the response message for GetPurchasesByDomain RPC
 *
 * Generated from protobuf message <code>purchases.GetPurchasesByDomainResponse</code>
 */
class GetPurchasesByDomainResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The list of purchases for the requested domain
     *
     * Generated from protobuf field <code>repeated .purchases.Purchase purchases = 1 [json_name = "purchases"];</code>
     */
    private $purchases;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Purchases\Purchase[] $purchases
     *           The list of purchases for the requested domain
     * }
     */
    public function __construct($data = NULL) {
        \Purchases\GPBMetadata\Purchases::initOnce();
        parent::__construct($data);
    }

    /**
     * The list of purchases for the requested domain
     *
     * Generated from protobuf field <code>repeated .purchases.Purchase purchases = 1 [json_name = "purchases"];</code>
     * @return RepeatedField<\Purchases\Purchase>
     */
    public function getPurchases()
    {
        return $this->purchases;
    }

    /**
     * The list of purchases for the requested domain
     *
     * Generated from protobuf field <code>repeated .purchases.Purchase purchases = 1 [json_name = "purchases"];</code>
     * @param \Purchases\Purchase[] $var
     * @return $this
     */
    public function setPurchases($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Purchases\Purchase::class);
        $this->purchases = $arr;

        return $this;
    }

}

