// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: purchases/purchases.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "purchases";

/** GetPurchasesByDomainRequest is the request message for GetPurchasesByDomain RPC */
export interface GetPurchasesByDomainRequest {
  /** The shop domain to query purchases for (e.g., "sw9.service.com") */
  domain: string;
}

/** GetPurchasesByDomainResponse is the response message for GetPurchasesByDomain RPC */
export interface GetPurchasesByDomainResponse {
  /** The list of purchases for the requested domain */
  purchases: Purchase[];
}

/** Purchase represents a single purchase/subscription record */
export interface Purchase {
  /** Name of the purchased plugin/extension */
  pluginName: string;
  /** Unique identifier for the purchase variant (e.g., "SwagCommercialBasic-1m") */
  identifier: string;
  /** Next billing date in ISO 8601 format (e.g., "2025-01-15") */
  nextBookingDate: string;
  /** Quantity of licenses purchased */
  quantity: number;
  /** Identifier of pending downgrade, if any (null if no pending downgrade) */
  pendingDowngradeIdentifier?: string | undefined;
}

function createBaseGetPurchasesByDomainRequest(): GetPurchasesByDomainRequest {
  return { domain: "" };
}

export const GetPurchasesByDomainRequest: MessageFns<GetPurchasesByDomainRequest> = {
  encode(message: GetPurchasesByDomainRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.domain !== "") {
      writer.uint32(10).string(message.domain);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPurchasesByDomainRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPurchasesByDomainRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.domain = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetPurchasesByDomainRequest {
    return { domain: isSet(object.domain) ? globalThis.String(object.domain) : "" };
  },

  toJSON(message: GetPurchasesByDomainRequest): unknown {
    const obj: any = {};
    if (message.domain !== "") {
      obj.domain = message.domain;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPurchasesByDomainRequest>, I>>(base?: I): GetPurchasesByDomainRequest {
    return GetPurchasesByDomainRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPurchasesByDomainRequest>, I>>(object: I): GetPurchasesByDomainRequest {
    const message = createBaseGetPurchasesByDomainRequest();
    message.domain = object.domain ?? "";
    return message;
  },
};

function createBaseGetPurchasesByDomainResponse(): GetPurchasesByDomainResponse {
  return { purchases: [] };
}

export const GetPurchasesByDomainResponse: MessageFns<GetPurchasesByDomainResponse> = {
  encode(message: GetPurchasesByDomainResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.purchases) {
      Purchase.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPurchasesByDomainResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPurchasesByDomainResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.purchases.push(Purchase.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetPurchasesByDomainResponse {
    return {
      purchases: globalThis.Array.isArray(object?.purchases)
        ? object.purchases.map((e: any) => Purchase.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GetPurchasesByDomainResponse): unknown {
    const obj: any = {};
    if (message.purchases?.length) {
      obj.purchases = message.purchases.map((e) => Purchase.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPurchasesByDomainResponse>, I>>(base?: I): GetPurchasesByDomainResponse {
    return GetPurchasesByDomainResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPurchasesByDomainResponse>, I>>(object: I): GetPurchasesByDomainResponse {
    const message = createBaseGetPurchasesByDomainResponse();
    message.purchases = object.purchases?.map((e) => Purchase.fromPartial(e)) || [];
    return message;
  },
};

function createBasePurchase(): Purchase {
  return { pluginName: "", identifier: "", nextBookingDate: "", quantity: 0, pendingDowngradeIdentifier: undefined };
}

export const Purchase: MessageFns<Purchase> = {
  encode(message: Purchase, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pluginName !== "") {
      writer.uint32(10).string(message.pluginName);
    }
    if (message.identifier !== "") {
      writer.uint32(18).string(message.identifier);
    }
    if (message.nextBookingDate !== "") {
      writer.uint32(26).string(message.nextBookingDate);
    }
    if (message.quantity !== 0) {
      writer.uint32(32).int32(message.quantity);
    }
    if (message.pendingDowngradeIdentifier !== undefined) {
      writer.uint32(42).string(message.pendingDowngradeIdentifier);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Purchase {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePurchase();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pluginName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.identifier = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.nextBookingDate = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.quantity = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.pendingDowngradeIdentifier = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Purchase {
    return {
      pluginName: isSet(object.pluginName) ? globalThis.String(object.pluginName) : "",
      identifier: isSet(object.identifier) ? globalThis.String(object.identifier) : "",
      nextBookingDate: isSet(object.nextBookingDate) ? globalThis.String(object.nextBookingDate) : "",
      quantity: isSet(object.quantity) ? globalThis.Number(object.quantity) : 0,
      pendingDowngradeIdentifier: isSet(object.pendingDowngradeIdentifier)
        ? globalThis.String(object.pendingDowngradeIdentifier)
        : undefined,
    };
  },

  toJSON(message: Purchase): unknown {
    const obj: any = {};
    if (message.pluginName !== "") {
      obj.pluginName = message.pluginName;
    }
    if (message.identifier !== "") {
      obj.identifier = message.identifier;
    }
    if (message.nextBookingDate !== "") {
      obj.nextBookingDate = message.nextBookingDate;
    }
    if (message.quantity !== 0) {
      obj.quantity = Math.round(message.quantity);
    }
    if (message.pendingDowngradeIdentifier !== undefined) {
      obj.pendingDowngradeIdentifier = message.pendingDowngradeIdentifier;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Purchase>, I>>(base?: I): Purchase {
    return Purchase.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Purchase>, I>>(object: I): Purchase {
    const message = createBasePurchase();
    message.pluginName = object.pluginName ?? "";
    message.identifier = object.identifier ?? "";
    message.nextBookingDate = object.nextBookingDate ?? "";
    message.quantity = object.quantity ?? 0;
    message.pendingDowngradeIdentifier = object.pendingDowngradeIdentifier ?? undefined;
    return message;
  },
};

/**
 * PurchasesService provides access to cached purchase/subscription data
 * synchronized from the SBP API and stored in Redis by domain.
 */
export type PurchasesServiceService = typeof PurchasesServiceService;
export const PurchasesServiceService = {
  /**
   * GetPurchasesByDomain retrieves all purchases for a specific shop domain.
   * The domain should be passed as a query parameter (e.g., "sw9.service.com").
   */
  getPurchasesByDomain: {
    path: "/purchases.PurchasesService/GetPurchasesByDomain",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetPurchasesByDomainRequest) =>
      Buffer.from(GetPurchasesByDomainRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => GetPurchasesByDomainRequest.decode(value),
    responseSerialize: (value: GetPurchasesByDomainResponse) =>
      Buffer.from(GetPurchasesByDomainResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => GetPurchasesByDomainResponse.decode(value),
  },
} as const;

export interface PurchasesServiceServer extends UntypedServiceImplementation {
  /**
   * GetPurchasesByDomain retrieves all purchases for a specific shop domain.
   * The domain should be passed as a query parameter (e.g., "sw9.service.com").
   */
  getPurchasesByDomain: handleUnaryCall<GetPurchasesByDomainRequest, GetPurchasesByDomainResponse>;
}

export interface PurchasesServiceClient extends Client {
  /**
   * GetPurchasesByDomain retrieves all purchases for a specific shop domain.
   * The domain should be passed as a query parameter (e.g., "sw9.service.com").
   */
  getPurchasesByDomain(
    request: GetPurchasesByDomainRequest,
    callback: (error: ServiceError | null, response: GetPurchasesByDomainResponse) => void,
  ): ClientUnaryCall;
  getPurchasesByDomain(
    request: GetPurchasesByDomainRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetPurchasesByDomainResponse) => void,
  ): ClientUnaryCall;
  getPurchasesByDomain(
    request: GetPurchasesByDomainRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetPurchasesByDomainResponse) => void,
  ): ClientUnaryCall;
}

export const PurchasesServiceClient = makeGenericClientConstructor(
  PurchasesServiceService,
  "purchases.PurchasesService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): PurchasesServiceClient;
  service: typeof PurchasesServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
