// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: purchases/purchases.proto

package purchases

import (
	_ "github.com/shopware/transaction-gateway/pkg/proto/go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetPurchasesByDomainRequest is the request message for GetPurchasesByDomain RPC
type GetPurchasesByDomainRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The shop domain to query purchases for (e.g., "sw9.service.com")
	Domain        string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPurchasesByDomainRequest) Reset() {
	*x = GetPurchasesByDomainRequest{}
	mi := &file_purchases_purchases_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPurchasesByDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPurchasesByDomainRequest) ProtoMessage() {}

func (x *GetPurchasesByDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchases_purchases_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPurchasesByDomainRequest.ProtoReflect.Descriptor instead.
func (*GetPurchasesByDomainRequest) Descriptor() ([]byte, []int) {
	return file_purchases_purchases_proto_rawDescGZIP(), []int{0}
}

func (x *GetPurchasesByDomainRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

// GetPurchasesByDomainResponse is the response message for GetPurchasesByDomain RPC
type GetPurchasesByDomainResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of purchases for the requested domain
	Purchases     []*Purchase `protobuf:"bytes,1,rep,name=purchases,proto3" json:"purchases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPurchasesByDomainResponse) Reset() {
	*x = GetPurchasesByDomainResponse{}
	mi := &file_purchases_purchases_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPurchasesByDomainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPurchasesByDomainResponse) ProtoMessage() {}

func (x *GetPurchasesByDomainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchases_purchases_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPurchasesByDomainResponse.ProtoReflect.Descriptor instead.
func (*GetPurchasesByDomainResponse) Descriptor() ([]byte, []int) {
	return file_purchases_purchases_proto_rawDescGZIP(), []int{1}
}

func (x *GetPurchasesByDomainResponse) GetPurchases() []*Purchase {
	if x != nil {
		return x.Purchases
	}
	return nil
}

// Purchase represents a single purchase/subscription record
type Purchase struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the purchased plugin/extension
	PluginName string `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	// Unique identifier for the purchase variant (e.g., "SwagCommercialBasic-1m")
	Identifier string `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// Next billing date in ISO 8601 format (e.g., "2025-01-15")
	NextBookingDate string `protobuf:"bytes,3,opt,name=next_booking_date,json=nextBookingDate,proto3" json:"next_booking_date,omitempty"`
	// Quantity of licenses purchased
	Quantity int32 `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// Identifier of pending downgrade, if any (null if no pending downgrade)
	PendingDowngradeIdentifier *string `protobuf:"bytes,5,opt,name=pending_downgrade_identifier,json=pendingDowngradeIdentifier,proto3,oneof" json:"pending_downgrade_identifier,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Purchase) Reset() {
	*x = Purchase{}
	mi := &file_purchases_purchases_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Purchase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Purchase) ProtoMessage() {}

func (x *Purchase) ProtoReflect() protoreflect.Message {
	mi := &file_purchases_purchases_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Purchase.ProtoReflect.Descriptor instead.
func (*Purchase) Descriptor() ([]byte, []int) {
	return file_purchases_purchases_proto_rawDescGZIP(), []int{2}
}

func (x *Purchase) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *Purchase) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *Purchase) GetNextBookingDate() string {
	if x != nil {
		return x.NextBookingDate
	}
	return ""
}

func (x *Purchase) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Purchase) GetPendingDowngradeIdentifier() string {
	if x != nil && x.PendingDowngradeIdentifier != nil {
		return *x.PendingDowngradeIdentifier
	}
	return ""
}

var File_purchases_purchases_proto protoreflect.FileDescriptor

const file_purchases_purchases_proto_rawDesc = "" +
	"\n" +
	"\x19purchases/purchases.proto\x12\tpurchases\x1a\x14common/options.proto\"5\n" +
	"\x1bGetPurchasesByDomainRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"Q\n" +
	"\x1cGetPurchasesByDomainResponse\x121\n" +
	"\tpurchases\x18\x01 \x03(\v2\x13.purchases.PurchaseR\tpurchases\"\xfb\x01\n" +
	"\bPurchase\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\x12*\n" +
	"\x11next_booking_date\x18\x03 \x01(\tR\x0fnextBookingDate\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12E\n" +
	"\x1cpending_downgrade_identifier\x18\x05 \x01(\tH\x00R\x1apendingDowngradeIdentifier\x88\x01\x01B\x1f\n" +
	"\x1d_pending_downgrade_identifier2\xcf\x02\n" +
	"\x10PurchasesService\x12g\n" +
	"\x14GetPurchasesByDomain\x12&.purchases.GetPurchasesByDomainRequest\x1a'.purchases.GetPurchasesByDomainResponse\x1a\xd1\x01\x8a\xb5\x18t\n" +
	"\fx-request-id\x1a>Request tracing ID for distributed tracing and log correlation\"$550e8400-e29b-41d4-a716-446655440000\x8a\xb5\x18U\n" +
	"\x11x-request-service\x10\x01\x1a(Request service name for log correlation\"\x14swag-copilot-serviceB\xa3\x01\n" +
	"\rcom.purchasesB\x0ePurchasesProtoP\x01Z>github.com/shopware/transaction-gateway/pkg/proto/go/purchases\xa2\x02\x03PXX\xaa\x02\tPurchases\xca\x02\tPurchases\xe2\x02\x15Purchases\\GPBMetadata\xea\x02\tPurchasesb\x06proto3"

var (
	file_purchases_purchases_proto_rawDescOnce sync.Once
	file_purchases_purchases_proto_rawDescData []byte
)

func file_purchases_purchases_proto_rawDescGZIP() []byte {
	file_purchases_purchases_proto_rawDescOnce.Do(func() {
		file_purchases_purchases_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_purchases_purchases_proto_rawDesc), len(file_purchases_purchases_proto_rawDesc)))
	})
	return file_purchases_purchases_proto_rawDescData
}

var file_purchases_purchases_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_purchases_purchases_proto_goTypes = []any{
	(*GetPurchasesByDomainRequest)(nil),  // 0: purchases.GetPurchasesByDomainRequest
	(*GetPurchasesByDomainResponse)(nil), // 1: purchases.GetPurchasesByDomainResponse
	(*Purchase)(nil),                     // 2: purchases.Purchase
}
var file_purchases_purchases_proto_depIdxs = []int32{
	2, // 0: purchases.GetPurchasesByDomainResponse.purchases:type_name -> purchases.Purchase
	0, // 1: purchases.PurchasesService.GetPurchasesByDomain:input_type -> purchases.GetPurchasesByDomainRequest
	1, // 2: purchases.PurchasesService.GetPurchasesByDomain:output_type -> purchases.GetPurchasesByDomainResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_purchases_purchases_proto_init() }
func file_purchases_purchases_proto_init() {
	if File_purchases_purchases_proto != nil {
		return
	}
	file_purchases_purchases_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_purchases_purchases_proto_rawDesc), len(file_purchases_purchases_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_purchases_purchases_proto_goTypes,
		DependencyIndexes: file_purchases_purchases_proto_depIdxs,
		MessageInfos:      file_purchases_purchases_proto_msgTypes,
	}.Build()
	File_purchases_purchases_proto = out.File
	file_purchases_purchases_proto_goTypes = nil
	file_purchases_purchases_proto_depIdxs = nil
}
