// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: purchases/purchases.proto

package purchases

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PurchasesService_GetPurchasesByDomain_FullMethodName = "/purchases.PurchasesService/GetPurchasesByDomain"
)

// PurchasesServiceClient is the client API for PurchasesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PurchasesService provides access to cached purchase/subscription data
// synchronized from the SBP API and stored in Redis by domain.
type PurchasesServiceClient interface {
	// GetPurchasesByDomain retrieves all purchases for a specific shop domain.
	// The domain should be passed as a query parameter (e.g., "sw9.service.com").
	GetPurchasesByDomain(ctx context.Context, in *GetPurchasesByDomainRequest, opts ...grpc.CallOption) (*GetPurchasesByDomainResponse, error)
}

type purchasesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPurchasesServiceClient(cc grpc.ClientConnInterface) PurchasesServiceClient {
	return &purchasesServiceClient{cc}
}

func (c *purchasesServiceClient) GetPurchasesByDomain(ctx context.Context, in *GetPurchasesByDomainRequest, opts ...grpc.CallOption) (*GetPurchasesByDomainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPurchasesByDomainResponse)
	err := c.cc.Invoke(ctx, PurchasesService_GetPurchasesByDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PurchasesServiceServer is the server API for PurchasesService service.
// All implementations must embed UnimplementedPurchasesServiceServer
// for forward compatibility.
//
// PurchasesService provides access to cached purchase/subscription data
// synchronized from the SBP API and stored in Redis by domain.
type PurchasesServiceServer interface {
	// GetPurchasesByDomain retrieves all purchases for a specific shop domain.
	// The domain should be passed as a query parameter (e.g., "sw9.service.com").
	GetPurchasesByDomain(context.Context, *GetPurchasesByDomainRequest) (*GetPurchasesByDomainResponse, error)
	mustEmbedUnimplementedPurchasesServiceServer()
}

// UnimplementedPurchasesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPurchasesServiceServer struct{}

func (UnimplementedPurchasesServiceServer) GetPurchasesByDomain(context.Context, *GetPurchasesByDomainRequest) (*GetPurchasesByDomainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPurchasesByDomain not implemented")
}
func (UnimplementedPurchasesServiceServer) mustEmbedUnimplementedPurchasesServiceServer() {}
func (UnimplementedPurchasesServiceServer) testEmbeddedByValue()                          {}

// UnsafePurchasesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PurchasesServiceServer will
// result in compilation errors.
type UnsafePurchasesServiceServer interface {
	mustEmbedUnimplementedPurchasesServiceServer()
}

func RegisterPurchasesServiceServer(s grpc.ServiceRegistrar, srv PurchasesServiceServer) {
	// If the following call panics, it indicates UnimplementedPurchasesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PurchasesService_ServiceDesc, srv)
}

func _PurchasesService_GetPurchasesByDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPurchasesByDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchasesServiceServer).GetPurchasesByDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PurchasesService_GetPurchasesByDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchasesServiceServer).GetPurchasesByDomain(ctx, req.(*GetPurchasesByDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PurchasesService_ServiceDesc is the grpc.ServiceDesc for PurchasesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PurchasesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "purchases.PurchasesService",
	HandlerType: (*PurchasesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPurchasesByDomain",
			Handler:    _PurchasesService_GetPurchasesByDomain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "purchases/purchases.proto",
}
