// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: auth/v1/auth.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Struct } from "../../google/protobuf/struct";

export const protobufPackage = "transaction.auth.v1";

export interface ExchangeCodeRequest {
  authorizationCode: string;
  /** Client's redirect URI used in OAuth flow */
  redirectUri: string;
}

export interface ExchangeCodeResponse {
  accessToken: string;
  refreshToken: string;
  expiresIn: number;
}

export interface RefreshTokenRequest {
  /** The refresh token to use for obtaining new tokens */
  refreshToken: string;
}

export interface RefreshTokenResponse {
  accessToken: string;
  /** New refresh token (token rotation) */
  refreshToken: string;
  expiresIn: number;
}

export interface GetUserAccountRequest {
  accessToken: string;
}

export interface GetUserAccountResponse {
  user: { [key: string]: any } | undefined;
}

function createBaseExchangeCodeRequest(): ExchangeCodeRequest {
  return { authorizationCode: "", redirectUri: "" };
}

export const ExchangeCodeRequest: MessageFns<ExchangeCodeRequest> = {
  encode(message: ExchangeCodeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authorizationCode !== "") {
      writer.uint32(10).string(message.authorizationCode);
    }
    if (message.redirectUri !== "") {
      writer.uint32(18).string(message.redirectUri);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExchangeCodeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExchangeCodeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.authorizationCode = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.redirectUri = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExchangeCodeRequest {
    return {
      authorizationCode: isSet(object.authorizationCode) ? globalThis.String(object.authorizationCode) : "",
      redirectUri: isSet(object.redirectUri) ? globalThis.String(object.redirectUri) : "",
    };
  },

  toJSON(message: ExchangeCodeRequest): unknown {
    const obj: any = {};
    if (message.authorizationCode !== "") {
      obj.authorizationCode = message.authorizationCode;
    }
    if (message.redirectUri !== "") {
      obj.redirectUri = message.redirectUri;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExchangeCodeRequest>, I>>(base?: I): ExchangeCodeRequest {
    return ExchangeCodeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExchangeCodeRequest>, I>>(object: I): ExchangeCodeRequest {
    const message = createBaseExchangeCodeRequest();
    message.authorizationCode = object.authorizationCode ?? "";
    message.redirectUri = object.redirectUri ?? "";
    return message;
  },
};

function createBaseExchangeCodeResponse(): ExchangeCodeResponse {
  return { accessToken: "", refreshToken: "", expiresIn: 0 };
}

export const ExchangeCodeResponse: MessageFns<ExchangeCodeResponse> = {
  encode(message: ExchangeCodeResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.accessToken !== "") {
      writer.uint32(10).string(message.accessToken);
    }
    if (message.refreshToken !== "") {
      writer.uint32(18).string(message.refreshToken);
    }
    if (message.expiresIn !== 0) {
      writer.uint32(24).int64(message.expiresIn);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExchangeCodeResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExchangeCodeResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.accessToken = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.refreshToken = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.expiresIn = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExchangeCodeResponse {
    return {
      accessToken: isSet(object.accessToken) ? globalThis.String(object.accessToken) : "",
      refreshToken: isSet(object.refreshToken) ? globalThis.String(object.refreshToken) : "",
      expiresIn: isSet(object.expiresIn) ? globalThis.Number(object.expiresIn) : 0,
    };
  },

  toJSON(message: ExchangeCodeResponse): unknown {
    const obj: any = {};
    if (message.accessToken !== "") {
      obj.accessToken = message.accessToken;
    }
    if (message.refreshToken !== "") {
      obj.refreshToken = message.refreshToken;
    }
    if (message.expiresIn !== 0) {
      obj.expiresIn = Math.round(message.expiresIn);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExchangeCodeResponse>, I>>(base?: I): ExchangeCodeResponse {
    return ExchangeCodeResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExchangeCodeResponse>, I>>(object: I): ExchangeCodeResponse {
    const message = createBaseExchangeCodeResponse();
    message.accessToken = object.accessToken ?? "";
    message.refreshToken = object.refreshToken ?? "";
    message.expiresIn = object.expiresIn ?? 0;
    return message;
  },
};

function createBaseRefreshTokenRequest(): RefreshTokenRequest {
  return { refreshToken: "" };
}

export const RefreshTokenRequest: MessageFns<RefreshTokenRequest> = {
  encode(message: RefreshTokenRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.refreshToken !== "") {
      writer.uint32(10).string(message.refreshToken);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RefreshTokenRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRefreshTokenRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.refreshToken = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RefreshTokenRequest {
    return { refreshToken: isSet(object.refreshToken) ? globalThis.String(object.refreshToken) : "" };
  },

  toJSON(message: RefreshTokenRequest): unknown {
    const obj: any = {};
    if (message.refreshToken !== "") {
      obj.refreshToken = message.refreshToken;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RefreshTokenRequest>, I>>(base?: I): RefreshTokenRequest {
    return RefreshTokenRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RefreshTokenRequest>, I>>(object: I): RefreshTokenRequest {
    const message = createBaseRefreshTokenRequest();
    message.refreshToken = object.refreshToken ?? "";
    return message;
  },
};

function createBaseRefreshTokenResponse(): RefreshTokenResponse {
  return { accessToken: "", refreshToken: "", expiresIn: 0 };
}

export const RefreshTokenResponse: MessageFns<RefreshTokenResponse> = {
  encode(message: RefreshTokenResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.accessToken !== "") {
      writer.uint32(10).string(message.accessToken);
    }
    if (message.refreshToken !== "") {
      writer.uint32(18).string(message.refreshToken);
    }
    if (message.expiresIn !== 0) {
      writer.uint32(24).int64(message.expiresIn);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RefreshTokenResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRefreshTokenResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.accessToken = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.refreshToken = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.expiresIn = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RefreshTokenResponse {
    return {
      accessToken: isSet(object.accessToken) ? globalThis.String(object.accessToken) : "",
      refreshToken: isSet(object.refreshToken) ? globalThis.String(object.refreshToken) : "",
      expiresIn: isSet(object.expiresIn) ? globalThis.Number(object.expiresIn) : 0,
    };
  },

  toJSON(message: RefreshTokenResponse): unknown {
    const obj: any = {};
    if (message.accessToken !== "") {
      obj.accessToken = message.accessToken;
    }
    if (message.refreshToken !== "") {
      obj.refreshToken = message.refreshToken;
    }
    if (message.expiresIn !== 0) {
      obj.expiresIn = Math.round(message.expiresIn);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RefreshTokenResponse>, I>>(base?: I): RefreshTokenResponse {
    return RefreshTokenResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RefreshTokenResponse>, I>>(object: I): RefreshTokenResponse {
    const message = createBaseRefreshTokenResponse();
    message.accessToken = object.accessToken ?? "";
    message.refreshToken = object.refreshToken ?? "";
    message.expiresIn = object.expiresIn ?? 0;
    return message;
  },
};

function createBaseGetUserAccountRequest(): GetUserAccountRequest {
  return { accessToken: "" };
}

export const GetUserAccountRequest: MessageFns<GetUserAccountRequest> = {
  encode(message: GetUserAccountRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.accessToken !== "") {
      writer.uint32(10).string(message.accessToken);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserAccountRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserAccountRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.accessToken = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetUserAccountRequest {
    return { accessToken: isSet(object.accessToken) ? globalThis.String(object.accessToken) : "" };
  },

  toJSON(message: GetUserAccountRequest): unknown {
    const obj: any = {};
    if (message.accessToken !== "") {
      obj.accessToken = message.accessToken;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetUserAccountRequest>, I>>(base?: I): GetUserAccountRequest {
    return GetUserAccountRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetUserAccountRequest>, I>>(object: I): GetUserAccountRequest {
    const message = createBaseGetUserAccountRequest();
    message.accessToken = object.accessToken ?? "";
    return message;
  },
};

function createBaseGetUserAccountResponse(): GetUserAccountResponse {
  return { user: undefined };
}

export const GetUserAccountResponse: MessageFns<GetUserAccountResponse> = {
  encode(message: GetUserAccountResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user !== undefined) {
      Struct.encode(Struct.wrap(message.user), writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserAccountResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserAccountResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user = Struct.unwrap(Struct.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetUserAccountResponse {
    return { user: isObject(object.user) ? object.user : undefined };
  },

  toJSON(message: GetUserAccountResponse): unknown {
    const obj: any = {};
    if (message.user !== undefined) {
      obj.user = message.user;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetUserAccountResponse>, I>>(base?: I): GetUserAccountResponse {
    return GetUserAccountResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetUserAccountResponse>, I>>(object: I): GetUserAccountResponse {
    const message = createBaseGetUserAccountResponse();
    message.user = object.user ?? undefined;
    return message;
  },
};

/**
 * AuthService provides OAuth 2.0 authentication and token management.
 * This service handles the OAuth flow itself, so it does NOT require authentication.
 */
export type AuthServiceService = typeof AuthServiceService;
export const AuthServiceService = {
  /**
   * ExchangeCode exchanges an OAuth authorization code for access and refresh tokens.
   * This is the first step after user completes OAuth consent flow.
   */
  exchangeCode: {
    path: "/transaction.auth.v1.AuthService/ExchangeCode",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ExchangeCodeRequest) => Buffer.from(ExchangeCodeRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => ExchangeCodeRequest.decode(value),
    responseSerialize: (value: ExchangeCodeResponse) => Buffer.from(ExchangeCodeResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => ExchangeCodeResponse.decode(value),
  },
  /**
   * RefreshToken refreshes an expired access token using the provided refresh token.
   * Use this when the access token has expired but refresh token is still valid.
   */
  refreshToken: {
    path: "/transaction.auth.v1.AuthService/RefreshToken",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: RefreshTokenRequest) => Buffer.from(RefreshTokenRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => RefreshTokenRequest.decode(value),
    responseSerialize: (value: RefreshTokenResponse) => Buffer.from(RefreshTokenResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => RefreshTokenResponse.decode(value),
  },
  /**
   * GetUserAccount fetches OIDC userinfo for a given access token.
   * Returns user profile information from the identity provider.
   */
  getUserAccount: {
    path: "/transaction.auth.v1.AuthService/GetUserAccount",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetUserAccountRequest) => Buffer.from(GetUserAccountRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => GetUserAccountRequest.decode(value),
    responseSerialize: (value: GetUserAccountResponse) => Buffer.from(GetUserAccountResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => GetUserAccountResponse.decode(value),
  },
} as const;

export interface AuthServiceServer extends UntypedServiceImplementation {
  /**
   * ExchangeCode exchanges an OAuth authorization code for access and refresh tokens.
   * This is the first step after user completes OAuth consent flow.
   */
  exchangeCode: handleUnaryCall<ExchangeCodeRequest, ExchangeCodeResponse>;
  /**
   * RefreshToken refreshes an expired access token using the provided refresh token.
   * Use this when the access token has expired but refresh token is still valid.
   */
  refreshToken: handleUnaryCall<RefreshTokenRequest, RefreshTokenResponse>;
  /**
   * GetUserAccount fetches OIDC userinfo for a given access token.
   * Returns user profile information from the identity provider.
   */
  getUserAccount: handleUnaryCall<GetUserAccountRequest, GetUserAccountResponse>;
}

export interface AuthServiceClient extends Client {
  /**
   * ExchangeCode exchanges an OAuth authorization code for access and refresh tokens.
   * This is the first step after user completes OAuth consent flow.
   */
  exchangeCode(
    request: ExchangeCodeRequest,
    callback: (error: ServiceError | null, response: ExchangeCodeResponse) => void,
  ): ClientUnaryCall;
  exchangeCode(
    request: ExchangeCodeRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ExchangeCodeResponse) => void,
  ): ClientUnaryCall;
  exchangeCode(
    request: ExchangeCodeRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ExchangeCodeResponse) => void,
  ): ClientUnaryCall;
  /**
   * RefreshToken refreshes an expired access token using the provided refresh token.
   * Use this when the access token has expired but refresh token is still valid.
   */
  refreshToken(
    request: RefreshTokenRequest,
    callback: (error: ServiceError | null, response: RefreshTokenResponse) => void,
  ): ClientUnaryCall;
  refreshToken(
    request: RefreshTokenRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: RefreshTokenResponse) => void,
  ): ClientUnaryCall;
  refreshToken(
    request: RefreshTokenRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: RefreshTokenResponse) => void,
  ): ClientUnaryCall;
  /**
   * GetUserAccount fetches OIDC userinfo for a given access token.
   * Returns user profile information from the identity provider.
   */
  getUserAccount(
    request: GetUserAccountRequest,
    callback: (error: ServiceError | null, response: GetUserAccountResponse) => void,
  ): ClientUnaryCall;
  getUserAccount(
    request: GetUserAccountRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetUserAccountResponse) => void,
  ): ClientUnaryCall;
  getUserAccount(
    request: GetUserAccountRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetUserAccountResponse) => void,
  ): ClientUnaryCall;
}

export const AuthServiceClient = makeGenericClientConstructor(
  AuthServiceService,
  "transaction.auth.v1.AuthService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): AuthServiceClient;
  service: typeof AuthServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
