<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: iap/v1/iap.proto

namespace Transaction\Iap\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>transaction.iap.v1.CalculateBasketResponse</code>
 */
class CalculateBasketResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double tax_rate = 1 [json_name = "taxRate"];</code>
     */
    protected $tax_rate = 0.0;
    /**
     * Generated from protobuf field <code>repeated .transaction.iap.v1.BasketPosition positions = 2 [json_name = "positions"];</code>
     */
    private $positions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $tax_rate
     *     @type \Transaction\Iap\V1\BasketPosition[] $positions
     * }
     */
    public function __construct($data = NULL) {
        \Transaction\Iap\V1\GPBMetadata\Iap::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double tax_rate = 1 [json_name = "taxRate"];</code>
     * @return float
     */
    public function getTaxRate()
    {
        return $this->tax_rate;
    }

    /**
     * Generated from protobuf field <code>double tax_rate = 1 [json_name = "taxRate"];</code>
     * @param float $var
     * @return $this
     */
    public function setTaxRate($var)
    {
        GPBUtil::checkDouble($var);
        $this->tax_rate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .transaction.iap.v1.BasketPosition positions = 2 [json_name = "positions"];</code>
     * @return RepeatedField<\Transaction\Iap\V1\BasketPosition>
     */
    public function getPositions()
    {
        return $this->positions;
    }

    /**
     * Generated from protobuf field <code>repeated .transaction.iap.v1.BasketPosition positions = 2 [json_name = "positions"];</code>
     * @param \Transaction\Iap\V1\BasketPosition[] $var
     * @return $this
     */
    public function setPositions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Transaction\Iap\V1\BasketPosition::class);
        $this->positions = $arr;

        return $this;
    }

}

