<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: iap/v1/iap.proto

namespace Transaction\Iap\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>transaction.iap.v1.GetInAppPlansResponse</code>
 */
class GetInAppPlansResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .transaction.iap.v1.InAppPlan plans = 1 [json_name = "plans"];</code>
     */
    private $plans;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Transaction\Iap\V1\InAppPlan[] $plans
     * }
     */
    public function __construct($data = NULL) {
        \Transaction\Iap\V1\GPBMetadata\Iap::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .transaction.iap.v1.InAppPlan plans = 1 [json_name = "plans"];</code>
     * @return RepeatedField<\Transaction\Iap\V1\InAppPlan>
     */
    public function getPlans()
    {
        return $this->plans;
    }

    /**
     * Generated from protobuf field <code>repeated .transaction.iap.v1.InAppPlan plans = 1 [json_name = "plans"];</code>
     * @param \Transaction\Iap\V1\InAppPlan[] $var
     * @return $this
     */
    public function setPlans($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Transaction\Iap\V1\InAppPlan::class);
        $this->plans = $arr;

        return $this;
    }

}

