<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: iap/v1/iap.proto

namespace Transaction\Iap\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>transaction.iap.v1.InAppPlan</code>
 */
class InAppPlan extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1 [json_name = "id"];</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string identifier = 2 [json_name = "identifier"];</code>
     */
    protected $identifier = '';
    /**
     * Generated from protobuf field <code>string name = 3 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string description = 4 [json_name = "description"];</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>optional string service_conditions = 5 [json_name = "serviceConditions"];</code>
     */
    protected $service_conditions = null;
    /**
     * Generated from protobuf field <code>optional string website_gtc = 6 [json_name = "websiteGtc"];</code>
     */
    protected $website_gtc = null;
    /**
     * Generated from protobuf field <code>repeated .transaction.iap.v1.PriceModel price_models = 7 [json_name = "priceModels"];</code>
     */
    private $price_models;
    /**
     * Generated from protobuf field <code>.transaction.iap.v1.PriceModel price_model = 8 [json_name = "priceModel"];</code>
     */
    protected $price_model = null;
    /**
     * Generated from protobuf field <code>.transaction.iap.v1.PlanGroup group = 9 [json_name = "group"];</code>
     */
    protected $group = null;
    /**
     * Generated from protobuf field <code>string status = 10 [json_name = "status"];</code>
     */
    protected $status = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type string $identifier
     *     @type string $name
     *     @type string $description
     *     @type string $service_conditions
     *     @type string $website_gtc
     *     @type \Transaction\Iap\V1\PriceModel[] $price_models
     *     @type \Transaction\Iap\V1\PriceModel $price_model
     *     @type \Transaction\Iap\V1\PlanGroup $group
     *     @type string $status
     * }
     */
    public function __construct($data = NULL) {
        \Transaction\Iap\V1\GPBMetadata\Iap::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1 [json_name = "id"];</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1 [json_name = "id"];</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string identifier = 2 [json_name = "identifier"];</code>
     * @return string
     */
    public function getIdentifier()
    {
        return $this->identifier;
    }

    /**
     * Generated from protobuf field <code>string identifier = 2 [json_name = "identifier"];</code>
     * @param string $var
     * @return $this
     */
    public function setIdentifier($var)
    {
        GPBUtil::checkString($var, True);
        $this->identifier = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 3 [json_name = "name"];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 3 [json_name = "name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 4 [json_name = "description"];</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 4 [json_name = "description"];</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string service_conditions = 5 [json_name = "serviceConditions"];</code>
     * @return string
     */
    public function getServiceConditions()
    {
        return isset($this->service_conditions) ? $this->service_conditions : '';
    }

    public function hasServiceConditions()
    {
        return isset($this->service_conditions);
    }

    public function clearServiceConditions()
    {
        unset($this->service_conditions);
    }

    /**
     * Generated from protobuf field <code>optional string service_conditions = 5 [json_name = "serviceConditions"];</code>
     * @param string $var
     * @return $this
     */
    public function setServiceConditions($var)
    {
        GPBUtil::checkString($var, True);
        $this->service_conditions = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string website_gtc = 6 [json_name = "websiteGtc"];</code>
     * @return string
     */
    public function getWebsiteGtc()
    {
        return isset($this->website_gtc) ? $this->website_gtc : '';
    }

    public function hasWebsiteGtc()
    {
        return isset($this->website_gtc);
    }

    public function clearWebsiteGtc()
    {
        unset($this->website_gtc);
    }

    /**
     * Generated from protobuf field <code>optional string website_gtc = 6 [json_name = "websiteGtc"];</code>
     * @param string $var
     * @return $this
     */
    public function setWebsiteGtc($var)
    {
        GPBUtil::checkString($var, True);
        $this->website_gtc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .transaction.iap.v1.PriceModel price_models = 7 [json_name = "priceModels"];</code>
     * @return RepeatedField<\Transaction\Iap\V1\PriceModel>
     */
    public function getPriceModels()
    {
        return $this->price_models;
    }

    /**
     * Generated from protobuf field <code>repeated .transaction.iap.v1.PriceModel price_models = 7 [json_name = "priceModels"];</code>
     * @param \Transaction\Iap\V1\PriceModel[] $var
     * @return $this
     */
    public function setPriceModels($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Transaction\Iap\V1\PriceModel::class);
        $this->price_models = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.transaction.iap.v1.PriceModel price_model = 8 [json_name = "priceModel"];</code>
     * @return \Transaction\Iap\V1\PriceModel|null
     */
    public function getPriceModel()
    {
        return $this->price_model;
    }

    public function hasPriceModel()
    {
        return isset($this->price_model);
    }

    public function clearPriceModel()
    {
        unset($this->price_model);
    }

    /**
     * Generated from protobuf field <code>.transaction.iap.v1.PriceModel price_model = 8 [json_name = "priceModel"];</code>
     * @param \Transaction\Iap\V1\PriceModel $var
     * @return $this
     */
    public function setPriceModel($var)
    {
        GPBUtil::checkMessage($var, \Transaction\Iap\V1\PriceModel::class);
        $this->price_model = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.transaction.iap.v1.PlanGroup group = 9 [json_name = "group"];</code>
     * @return \Transaction\Iap\V1\PlanGroup|null
     */
    public function getGroup()
    {
        return $this->group;
    }

    public function hasGroup()
    {
        return isset($this->group);
    }

    public function clearGroup()
    {
        unset($this->group);
    }

    /**
     * Generated from protobuf field <code>.transaction.iap.v1.PlanGroup group = 9 [json_name = "group"];</code>
     * @param \Transaction\Iap\V1\PlanGroup $var
     * @return $this
     */
    public function setGroup($var)
    {
        GPBUtil::checkMessage($var, \Transaction\Iap\V1\PlanGroup::class);
        $this->group = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 10 [json_name = "status"];</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 10 [json_name = "status"];</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

}

