<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: iap/v1/iap.proto

namespace Transaction\Iap\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>transaction.iap.v1.PlaceOrderResponse</code>
 */
class PlaceOrderResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Define fields based on successful order response, usually empty or confirmation
     *
     * Generated from protobuf field <code>bool success = 1 [json_name = "success"];</code>
     */
    protected $success = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $success
     *           Define fields based on successful order response, usually empty or confirmation
     * }
     */
    public function __construct($data = NULL) {
        \Transaction\Iap\V1\GPBMetadata\Iap::initOnce();
        parent::__construct($data);
    }

    /**
     * Define fields based on successful order response, usually empty or confirmation
     *
     * Generated from protobuf field <code>bool success = 1 [json_name = "success"];</code>
     * @return bool
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * Define fields based on successful order response, usually empty or confirmation
     *
     * Generated from protobuf field <code>bool success = 1 [json_name = "success"];</code>
     * @param bool $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->success = $var;

        return $this;
    }

}

