<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: iap/v1/iap.proto

namespace Transaction\Iap\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>transaction.iap.v1.PlaceOrderRequest</code>
 */
class PlaceOrderRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double tax_rate = 1 [json_name = "taxRate"];</code>
     */
    protected $tax_rate = 0.0;
    /**
     * Generated from protobuf field <code>repeated .transaction.iap.v1.BasketPosition positions = 2 [json_name = "positions"];</code>
     */
    private $positions;
    /**
     * Generated from protobuf field <code>string language = 3 [json_name = "language"];</code>
     */
    protected $language = '';
    /**
     * Generated from protobuf field <code>string domain = 4 [json_name = "domain"];</code>
     */
    protected $domain = '';
    /**
     * Generated from protobuf field <code>string shopware_version = 5 [json_name = "shopwareVersion"];</code>
     */
    protected $shopware_version = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $tax_rate
     *     @type \Transaction\Iap\V1\BasketPosition[] $positions
     *     @type string $language
     *     @type string $domain
     *     @type string $shopware_version
     * }
     */
    public function __construct($data = NULL) {
        \Transaction\Iap\V1\GPBMetadata\Iap::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double tax_rate = 1 [json_name = "taxRate"];</code>
     * @return float
     */
    public function getTaxRate()
    {
        return $this->tax_rate;
    }

    /**
     * Generated from protobuf field <code>double tax_rate = 1 [json_name = "taxRate"];</code>
     * @param float $var
     * @return $this
     */
    public function setTaxRate($var)
    {
        GPBUtil::checkDouble($var);
        $this->tax_rate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .transaction.iap.v1.BasketPosition positions = 2 [json_name = "positions"];</code>
     * @return RepeatedField<\Transaction\Iap\V1\BasketPosition>
     */
    public function getPositions()
    {
        return $this->positions;
    }

    /**
     * Generated from protobuf field <code>repeated .transaction.iap.v1.BasketPosition positions = 2 [json_name = "positions"];</code>
     * @param \Transaction\Iap\V1\BasketPosition[] $var
     * @return $this
     */
    public function setPositions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Transaction\Iap\V1\BasketPosition::class);
        $this->positions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string language = 3 [json_name = "language"];</code>
     * @return string
     */
    public function getLanguage()
    {
        return $this->language;
    }

    /**
     * Generated from protobuf field <code>string language = 3 [json_name = "language"];</code>
     * @param string $var
     * @return $this
     */
    public function setLanguage($var)
    {
        GPBUtil::checkString($var, True);
        $this->language = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string domain = 4 [json_name = "domain"];</code>
     * @return string
     */
    public function getDomain()
    {
        return $this->domain;
    }

    /**
     * Generated from protobuf field <code>string domain = 4 [json_name = "domain"];</code>
     * @param string $var
     * @return $this
     */
    public function setDomain($var)
    {
        GPBUtil::checkString($var, True);
        $this->domain = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string shopware_version = 5 [json_name = "shopwareVersion"];</code>
     * @return string
     */
    public function getShopwareVersion()
    {
        return $this->shopware_version;
    }

    /**
     * Generated from protobuf field <code>string shopware_version = 5 [json_name = "shopwareVersion"];</code>
     * @param string $var
     * @return $this
     */
    public function setShopwareVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->shopware_version = $var;

        return $this;
    }

}

