<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: iap/v1/iap.proto

namespace Transaction\Iap\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>transaction.iap.v1.SubscriptionChange</code>
 */
class SubscriptionChange extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string type = 1 [json_name = "type"];</code>
     */
    protected $type = '';
    /**
     * Generated from protobuf field <code>string current_in_app_feature_identifier = 2 [json_name = "currentInAppFeatureIdentifier"];</code>
     */
    protected $current_in_app_feature_identifier = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $type
     *     @type string $current_in_app_feature_identifier
     * }
     */
    public function __construct($data = NULL) {
        \Transaction\Iap\V1\GPBMetadata\Iap::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string type = 1 [json_name = "type"];</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 1 [json_name = "type"];</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string current_in_app_feature_identifier = 2 [json_name = "currentInAppFeatureIdentifier"];</code>
     * @return string
     */
    public function getCurrentInAppFeatureIdentifier()
    {
        return $this->current_in_app_feature_identifier;
    }

    /**
     * Generated from protobuf field <code>string current_in_app_feature_identifier = 2 [json_name = "currentInAppFeatureIdentifier"];</code>
     * @param string $var
     * @return $this
     */
    public function setCurrentInAppFeatureIdentifier($var)
    {
        GPBUtil::checkString($var, True);
        $this->current_in_app_feature_identifier = $var;

        return $this;
    }

}

