// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: iap/v1/iap.proto

package iapv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IAPService_CalculateBasket_FullMethodName = "/transaction.iap.v1.IAPService/CalculateBasket"
	IAPService_PlaceOrder_FullMethodName      = "/transaction.iap.v1.IAPService/PlaceOrder"
	IAPService_GetInAppFeature_FullMethodName = "/transaction.iap.v1.IAPService/GetInAppFeature"
	IAPService_GetInAppPlans_FullMethodName   = "/transaction.iap.v1.IAPService/GetInAppPlans"
)

// IAPServiceClient is the client API for IAPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IAPService provides in-app purchase operations for Shopware extensions.
// All methods require OAuth authentication via metadata headers unless overridden at method level.
type IAPServiceClient interface {
	// CalculateBasket calculates pricing for a basket of in-app purchases.
	// Returns tax rates and itemized positions with pricing details.
	CalculateBasket(ctx context.Context, in *CalculateBasketRequest, opts ...grpc.CallOption) (*CalculateBasketResponse, error)
	// PlaceOrder finalizes an in-app purchase order.
	// Requires a previously calculated basket with valid positions.
	PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*PlaceOrderResponse, error)
	// GetInAppFeature retrieves details about a specific in-app feature.
	// Returns feature configuration and pricing variants.
	GetInAppFeature(ctx context.Context, in *GetInAppFeatureRequest, opts ...grpc.CallOption) (*GetInAppFeatureResponse, error)
	// GetInAppPlans retrieves all in-app plans for a specific extension.
	// This is a public API that uses M2M authentication (no user OAuth token required).
	GetInAppPlans(ctx context.Context, in *GetInAppPlansRequest, opts ...grpc.CallOption) (*GetInAppPlansResponse, error)
}

type iAPServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIAPServiceClient(cc grpc.ClientConnInterface) IAPServiceClient {
	return &iAPServiceClient{cc}
}

func (c *iAPServiceClient) CalculateBasket(ctx context.Context, in *CalculateBasketRequest, opts ...grpc.CallOption) (*CalculateBasketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateBasketResponse)
	err := c.cc.Invoke(ctx, IAPService_CalculateBasket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAPServiceClient) PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*PlaceOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaceOrderResponse)
	err := c.cc.Invoke(ctx, IAPService_PlaceOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAPServiceClient) GetInAppFeature(ctx context.Context, in *GetInAppFeatureRequest, opts ...grpc.CallOption) (*GetInAppFeatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInAppFeatureResponse)
	err := c.cc.Invoke(ctx, IAPService_GetInAppFeature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAPServiceClient) GetInAppPlans(ctx context.Context, in *GetInAppPlansRequest, opts ...grpc.CallOption) (*GetInAppPlansResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInAppPlansResponse)
	err := c.cc.Invoke(ctx, IAPService_GetInAppPlans_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IAPServiceServer is the server API for IAPService service.
// All implementations must embed UnimplementedIAPServiceServer
// for forward compatibility.
//
// IAPService provides in-app purchase operations for Shopware extensions.
// All methods require OAuth authentication via metadata headers unless overridden at method level.
type IAPServiceServer interface {
	// CalculateBasket calculates pricing for a basket of in-app purchases.
	// Returns tax rates and itemized positions with pricing details.
	CalculateBasket(context.Context, *CalculateBasketRequest) (*CalculateBasketResponse, error)
	// PlaceOrder finalizes an in-app purchase order.
	// Requires a previously calculated basket with valid positions.
	PlaceOrder(context.Context, *PlaceOrderRequest) (*PlaceOrderResponse, error)
	// GetInAppFeature retrieves details about a specific in-app feature.
	// Returns feature configuration and pricing variants.
	GetInAppFeature(context.Context, *GetInAppFeatureRequest) (*GetInAppFeatureResponse, error)
	// GetInAppPlans retrieves all in-app plans for a specific extension.
	// This is a public API that uses M2M authentication (no user OAuth token required).
	GetInAppPlans(context.Context, *GetInAppPlansRequest) (*GetInAppPlansResponse, error)
	mustEmbedUnimplementedIAPServiceServer()
}

// UnimplementedIAPServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIAPServiceServer struct{}

func (UnimplementedIAPServiceServer) CalculateBasket(context.Context, *CalculateBasketRequest) (*CalculateBasketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateBasket not implemented")
}
func (UnimplementedIAPServiceServer) PlaceOrder(context.Context, *PlaceOrderRequest) (*PlaceOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlaceOrder not implemented")
}
func (UnimplementedIAPServiceServer) GetInAppFeature(context.Context, *GetInAppFeatureRequest) (*GetInAppFeatureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInAppFeature not implemented")
}
func (UnimplementedIAPServiceServer) GetInAppPlans(context.Context, *GetInAppPlansRequest) (*GetInAppPlansResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInAppPlans not implemented")
}
func (UnimplementedIAPServiceServer) mustEmbedUnimplementedIAPServiceServer() {}
func (UnimplementedIAPServiceServer) testEmbeddedByValue()                    {}

// UnsafeIAPServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IAPServiceServer will
// result in compilation errors.
type UnsafeIAPServiceServer interface {
	mustEmbedUnimplementedIAPServiceServer()
}

func RegisterIAPServiceServer(s grpc.ServiceRegistrar, srv IAPServiceServer) {
	// If the following call panics, it indicates UnimplementedIAPServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IAPService_ServiceDesc, srv)
}

func _IAPService_CalculateBasket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateBasketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAPServiceServer).CalculateBasket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAPService_CalculateBasket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAPServiceServer).CalculateBasket(ctx, req.(*CalculateBasketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAPService_PlaceOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAPServiceServer).PlaceOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAPService_PlaceOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAPServiceServer).PlaceOrder(ctx, req.(*PlaceOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAPService_GetInAppFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInAppFeatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAPServiceServer).GetInAppFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAPService_GetInAppFeature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAPServiceServer).GetInAppFeature(ctx, req.(*GetInAppFeatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAPService_GetInAppPlans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInAppPlansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAPServiceServer).GetInAppPlans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAPService_GetInAppPlans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAPServiceServer).GetInAppPlans(ctx, req.(*GetInAppPlansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IAPService_ServiceDesc is the grpc.ServiceDesc for IAPService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IAPService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transaction.iap.v1.IAPService",
	HandlerType: (*IAPServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateBasket",
			Handler:    _IAPService_CalculateBasket_Handler,
		},
		{
			MethodName: "PlaceOrder",
			Handler:    _IAPService_PlaceOrder_Handler,
		},
		{
			MethodName: "GetInAppFeature",
			Handler:    _IAPService_GetInAppFeature_Handler,
		},
		{
			MethodName: "GetInAppPlans",
			Handler:    _IAPService_GetInAppPlans_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iap/v1/iap.proto",
}
