<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: purchases/v1/purchases.proto

namespace Transaction\Purchases\V1\GPBMetadata;

class Purchases
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Common\GPBMetadata\Options::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xC4\x08\x0A\x1Cpurchases/v1/purchases.proto\x12\x18transaction.purchases.v1\"5\x0A\x1BGetPurchasesByDomainRequest\x12\x16\x0A\x06domain\x18\x01 \x01(\x09R\x06domain\"`\x0A\x1CGetPurchasesByDomainResponse\x12@\x0A\x09purchases\x18\x01 \x03(\x0B2\".transaction.purchases.v1.PurchaseR\x09purchases\"\xFB\x01\x0A\x08Purchase\x12\x1F\x0A\x0Bplugin_name\x18\x01 \x01(\x09R\x0ApluginName\x12\x1E\x0A\x0Aidentifier\x18\x02 \x01(\x09R\x0Aidentifier\x12*\x0A\x11next_booking_date\x18\x03 \x01(\x09R\x0FnextBookingDate\x12\x1A\x0A\x08quantity\x18\x04 \x01(\x05R\x08quantity\x12E\x0A\x1Cpending_downgrade_identifier\x18\x05 \x01(\x09H\x00R\x1ApendingDowngradeIdentifier\x88\x01\x01B\x1F\x0A\x1D_pending_downgrade_identifier2\xEE\x02\x0A\x10PurchasesService\x12\x85\x01\x0A\x14GetPurchasesByDomain\x125.transaction.purchases.v1.GetPurchasesByDomainRequest\x1A6.transaction.purchases.v1.GetPurchasesByDomainResponse\x1A\xD1\x01\x8A\xB5\x18t\x0A\x0Cx-request-id\x1A>Request tracing ID for distributed tracing and log correlation\"\$550e8400-e29b-41d4-a716-446655440000\x8A\xB5\x18U\x0A\x11x-request-service\x10\x01\x1A(Request service name for log correlation\"\x14swag-copilot-serviceB\xF9\x01\x0A\x1Ccom.transaction.purchases.v1B\x0EPurchasesProtoP\x01ZGgithub.com/shopware/transaction-gateway-protos/purchases/v1;purchasesv1\xA2\x02\x03TPX\xAA\x02\x18Transaction.Purchases.V1\xCA\x02\x18Transaction\\Purchases\\V1\xE2\x02\$Transaction\\Purchases\\V1\\GPBMetadata\xEA\x02\x1ATransaction::Purchases::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

