<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/options.proto

namespace Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * MetadataHeader defines a gRPC metadata header requirement for a service or method.
 * Use this to document and enforce metadata contracts between services.
 * Example usage in proto:
 *   service MyService {
 *     option (common.service_metadata) = { name: "authorization" required: true };
 *     option (common.service_metadata) = { name: "x-request-id" required: false };
 *   }
 *
 * Generated from protobuf message <code>common.MetadataHeader</code>
 */
class MetadataHeader extends \Google\Protobuf\Internal\Message
{
    /**
     * The name of the metadata header (lowercase, e.g., "authorization", "x-request-id")
     *
     * Generated from protobuf field <code>string name = 1 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * Whether this header is required for the request to succeed
     *
     * Generated from protobuf field <code>bool required = 2 [json_name = "required"];</code>
     */
    protected $required = false;
    /**
     * Human-readable description of the header's purpose
     *
     * Generated from protobuf field <code>string description = 3 [json_name = "description"];</code>
     */
    protected $description = '';
    /**
     * Example value for documentation purposes
     *
     * Generated from protobuf field <code>string example = 4 [json_name = "example"];</code>
     */
    protected $example = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           The name of the metadata header (lowercase, e.g., "authorization", "x-request-id")
     *     @type bool $required
     *           Whether this header is required for the request to succeed
     *     @type string $description
     *           Human-readable description of the header's purpose
     *     @type string $example
     *           Example value for documentation purposes
     * }
     */
    public function __construct($data = NULL) {
        \Common\GPBMetadata\Options::initOnce();
        parent::__construct($data);
    }

    /**
     * The name of the metadata header (lowercase, e.g., "authorization", "x-request-id")
     *
     * Generated from protobuf field <code>string name = 1 [json_name = "name"];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The name of the metadata header (lowercase, e.g., "authorization", "x-request-id")
     *
     * Generated from protobuf field <code>string name = 1 [json_name = "name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Whether this header is required for the request to succeed
     *
     * Generated from protobuf field <code>bool required = 2 [json_name = "required"];</code>
     * @return bool
     */
    public function getRequired()
    {
        return $this->required;
    }

    /**
     * Whether this header is required for the request to succeed
     *
     * Generated from protobuf field <code>bool required = 2 [json_name = "required"];</code>
     * @param bool $var
     * @return $this
     */
    public function setRequired($var)
    {
        GPBUtil::checkBool($var);
        $this->required = $var;

        return $this;
    }

    /**
     * Human-readable description of the header's purpose
     *
     * Generated from protobuf field <code>string description = 3 [json_name = "description"];</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Human-readable description of the header's purpose
     *
     * Generated from protobuf field <code>string description = 3 [json_name = "description"];</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Example value for documentation purposes
     *
     * Generated from protobuf field <code>string example = 4 [json_name = "example"];</code>
     * @return string
     */
    public function getExample()
    {
        return $this->example;
    }

    /**
     * Example value for documentation purposes
     *
     * Generated from protobuf field <code>string example = 4 [json_name = "example"];</code>
     * @param string $var
     * @return $this
     */
    public function setExample($var)
    {
        GPBUtil::checkString($var, True);
        $this->example = $var;

        return $this;
    }

}

