// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common/options.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MetadataHeader defines a gRPC metadata header requirement for a service or method.
// Use this to document and enforce metadata contracts between services.
//
// Example usage in proto:
//
//	service MyService {
//	  option (common.service_metadata) = { name: "authorization" required: true };
//	  option (common.service_metadata) = { name: "x-request-id" required: false };
//	}
type MetadataHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the metadata header (lowercase, e.g., "authorization", "x-request-id")
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Whether this header is required for the request to succeed
	Required bool `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"`
	// Human-readable description of the header's purpose
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Example value for documentation purposes
	Example       string `protobuf:"bytes,4,opt,name=example,proto3" json:"example,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataHeader) Reset() {
	*x = MetadataHeader{}
	mi := &file_common_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataHeader) ProtoMessage() {}

func (x *MetadataHeader) ProtoReflect() protoreflect.Message {
	mi := &file_common_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataHeader.ProtoReflect.Descriptor instead.
func (*MetadataHeader) Descriptor() ([]byte, []int) {
	return file_common_options_proto_rawDescGZIP(), []int{0}
}

func (x *MetadataHeader) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetadataHeader) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *MetadataHeader) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MetadataHeader) GetExample() string {
	if x != nil {
		return x.Example
	}
	return ""
}

var file_common_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: ([]*MetadataHeader)(nil),
		Field:         50001,
		Name:          "common.service_metadata",
		Tag:           "bytes,50001,rep,name=service_metadata",
		Filename:      "common/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: ([]*MetadataHeader)(nil),
		Field:         50002,
		Name:          "common.method_metadata",
		Tag:           "bytes,50002,rep,name=method_metadata",
		Filename:      "common/options.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// Metadata headers required or optional for all methods in this service
	//
	// repeated common.MetadataHeader service_metadata = 50001;
	E_ServiceMetadata = &file_common_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// Metadata headers required or optional for this specific method
	//
	// repeated common.MetadataHeader method_metadata = 50002;
	E_MethodMetadata = &file_common_options_proto_extTypes[1]
)

var File_common_options_proto protoreflect.FileDescriptor

const file_common_options_proto_rawDesc = "" +
	"\n" +
	"\x14common/options.proto\x12\x06common\x1a google/protobuf/descriptor.proto\"|\n" +
	"\x0eMetadataHeader\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\brequired\x18\x02 \x01(\bR\brequired\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aexample\x18\x04 \x01(\tR\aexample:d\n" +
	"\x10service_metadata\x12\x1f.google.protobuf.ServiceOptions\x18ц\x03 \x03(\v2\x16.common.MetadataHeaderR\x0fserviceMetadata:a\n" +
	"\x0fmethod_metadata\x12\x1e.google.protobuf.MethodOptions\x18҆\x03 \x03(\v2\x16.common.MetadataHeaderR\x0emethodMetadataB\x89\x01\n" +
	"\n" +
	"com.commonB\fOptionsProtoP\x01Z5github.com/shopware/transaction-gateway-protos/common\xa2\x02\x03CXX\xaa\x02\x06Common\xca\x02\x06Common\xe2\x02\x12Common\\GPBMetadata\xea\x02\x06Commonb\x06proto3"

var (
	file_common_options_proto_rawDescOnce sync.Once
	file_common_options_proto_rawDescData []byte
)

func file_common_options_proto_rawDescGZIP() []byte {
	file_common_options_proto_rawDescOnce.Do(func() {
		file_common_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_options_proto_rawDesc), len(file_common_options_proto_rawDesc)))
	})
	return file_common_options_proto_rawDescData
}

var file_common_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_options_proto_goTypes = []any{
	(*MetadataHeader)(nil),              // 0: common.MetadataHeader
	(*descriptorpb.ServiceOptions)(nil), // 1: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 2: google.protobuf.MethodOptions
}
var file_common_options_proto_depIdxs = []int32{
	1, // 0: common.service_metadata:extendee -> google.protobuf.ServiceOptions
	2, // 1: common.method_metadata:extendee -> google.protobuf.MethodOptions
	0, // 2: common.service_metadata:type_name -> common.MetadataHeader
	0, // 3: common.method_metadata:type_name -> common.MetadataHeader
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	2, // [2:4] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_options_proto_init() }
func file_common_options_proto_init() {
	if File_common_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_options_proto_rawDesc), len(file_common_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_common_options_proto_goTypes,
		DependencyIndexes: file_common_options_proto_depIdxs,
		MessageInfos:      file_common_options_proto_msgTypes,
		ExtensionInfos:    file_common_options_proto_extTypes,
	}.Build()
	File_common_options_proto = out.File
	file_common_options_proto_goTypes = nil
	file_common_options_proto_depIdxs = nil
}
