// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: common/options.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "common";

/**
 * MetadataHeader defines a gRPC metadata header requirement for a service or method.
 * Use this to document and enforce metadata contracts between services.
 *
 * Example usage in proto:
 *   service MyService {
 *     option (common.service_metadata) = { name: "authorization" required: true };
 *     option (common.service_metadata) = { name: "x-request-id" required: false };
 *   }
 */
export interface MetadataHeader {
  /** The name of the metadata header (lowercase, e.g., "authorization", "x-request-id") */
  name: string;
  /** Whether this header is required for the request to succeed */
  required: boolean;
  /** Human-readable description of the header's purpose */
  description: string;
  /** Example value for documentation purposes */
  example: string;
}

function createBaseMetadataHeader(): MetadataHeader {
  return { name: "", required: false, description: "", example: "" };
}

export const MetadataHeader: MessageFns<MetadataHeader> = {
  encode(message: MetadataHeader, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.required !== false) {
      writer.uint32(16).bool(message.required);
    }
    if (message.description !== "") {
      writer.uint32(26).string(message.description);
    }
    if (message.example !== "") {
      writer.uint32(34).string(message.example);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MetadataHeader {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMetadataHeader();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.required = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.example = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MetadataHeader {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      required: isSet(object.required) ? globalThis.Boolean(object.required) : false,
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      example: isSet(object.example) ? globalThis.String(object.example) : "",
    };
  },

  toJSON(message: MetadataHeader): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.required !== false) {
      obj.required = message.required;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.example !== "") {
      obj.example = message.example;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MetadataHeader>, I>>(base?: I): MetadataHeader {
    return MetadataHeader.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MetadataHeader>, I>>(object: I): MetadataHeader {
    const message = createBaseMetadataHeader();
    message.name = object.name ?? "";
    message.required = object.required ?? false;
    message.description = object.description ?? "";
    message.example = object.example ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
