issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:shopware/transaction-gateway:.*
claim_pattern:
  workflow_ref: shopware/.*
permissions:
  contents: read
  pull_requests: write