<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth/v1/auth.proto

namespace Transaction\Auth\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>transaction.auth.v1.RefreshTokenRequest</code>
 */
class RefreshTokenRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The refresh token to use for obtaining new tokens
     *
     * Generated from protobuf field <code>string refresh_token = 1 [json_name = "refreshToken"];</code>
     */
    protected $refresh_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $refresh_token
     *           The refresh token to use for obtaining new tokens
     * }
     */
    public function __construct($data = NULL) {
        \Transaction\Auth\V1\GPBMetadata\Auth::initOnce();
        parent::__construct($data);
    }

    /**
     * The refresh token to use for obtaining new tokens
     *
     * Generated from protobuf field <code>string refresh_token = 1 [json_name = "refreshToken"];</code>
     * @return string
     */
    public function getRefreshToken()
    {
        return $this->refresh_token;
    }

    /**
     * The refresh token to use for obtaining new tokens
     *
     * Generated from protobuf field <code>string refresh_token = 1 [json_name = "refreshToken"];</code>
     * @param string $var
     * @return $this
     */
    public function setRefreshToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->refresh_token = $var;

        return $this;
    }

}

